import { SPACING } from '@/builder/define.ts';
import { STYLE_ATTR, STYLE_KEY_ORDER, STYLE_KEYS, type StyleKey } from '@/builder/style/model.ts';

/*
 * Spec §3.2 / §5.2 / §7: the static sheet keyed on data-sfs-* attributes. Every selector is (0,4,0):
 * above module classes and template part rules (0,3,0); a template's escape hatch at equal
 * specificity wins only because template CSS loads after the main bundle.
 */

const ON = ':root:root [data-sf-style]';
const sel = (key: StyleKey, value: string) => `${ON}[data-sfs-${STYLE_ATTR[key]}="${value}"]`;
const BORDER_WIDTH: Record<string, string> = { thin: '1px', medium: '2px', thick: '4px' };
const RADIUS: Record<string, string> = {
  none: '0', sm: 'var(--mantine-radius-sm)', md: 'var(--mantine-radius-md)', lg: 'var(--mantine-radius-lg)',
  card: 'var(--sf-card-radius)', pill: 'var(--sf-pill-radius)',
};
const SHADOW: Record<string, string> = { card: 'var(--sf-card-shadow)', raised: 'var(--sf-card-shadow-hover)' };
const TEXT_SCALE: Record<string, string> = { sm: '0.875', lg: '1.125', xl: '1.25' };
const MAX_WIDTH: Record<string, string> = { narrow: '36rem', text: '68ch', wide: '60rem' };
const SPACE = SPACING as Record<string, string>;
const BLOCK_PROP: Partial<Record<StyleKey, string>> = {
  padTop: 'padding-block-start', padBottom: 'padding-block-end', marginTop: 'margin-block-start', marginBottom: 'margin-block-end',
};

function declarations(key: StyleKey, value: string): string[] {
  const prop = BLOCK_PROP[key];
  if (prop) return [`${prop}: ${SPACE[value]}`];
  switch (key) {
    case 'bg': return [`background: var(--sf-${value})`];
    case 'fg': return [`color: var(--sf-${value})`, `--sf-block-fg: var(--sf-${value})`];
    case 'padX': return [`padding-inline: ${SPACE[value]}`];
    case 'border': return [`border: ${BORDER_WIDTH[value]} var(--sfs-bs, solid) var(--sfs-bc, var(--sf-line))`];
    case 'borderColor': return [`--sfs-bc: var(--sf-${value})`];
    case 'borderStyle': return [`--sfs-bs: ${value}`];
    case 'radius': return [`border-radius: ${RADIUS[value]}`];
    case 'shadow': return [`box-shadow: ${SHADOW[value]}`];
    case 'textSize': return [`--sf-text-scale: ${TEXT_SCALE[value]}`];
    case 'align': return [`text-align: ${value}`];
    case 'maxWidth': return [`max-width: min(${MAX_WIDTH[value]}, 100%)`];
    default: return [];
  }
}

const rule = (selector: string, lines: string[], indent = '') =>
  `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l};`).join('\n')}\n${indent}}\n`;
const media = (query: string, body: string[]) => `@media ${query} {\n${body.join('')}}\n`;

export function renderBlockStyleCss(): string {
  const out: string[] = [
    '/* Generated by renderBlockStyleCss() in css.ts. Do not edit: UPDATE_BLOCK_STYLE_CSS=1 npm --prefix web test -- test/block-style-css.test.ts rewrites it. */\n',
    rule(`${ON}[data-sf-style]`, ['box-sizing: border-box', 'min-width: 0', '--sfs-bc: initial', '--sfs-bs: initial']),
    rule(':root [data-sf-style]:not([data-sf-block]):empty', ['display: none']),
  ];
  for (const key of STYLE_KEY_ORDER) {
    if (key === 'hide') continue;
    for (const value of STYLE_KEYS[key]) out.push(rule(sel(key, value), declarations(key, value)));
  }
  // A bare background insets the block's text, except on the header part (its own inner
  // rail) and the WholesaleTable (its cart bar escapes the column full-bleed).
  out.push(rule(':root [data-sf-style][data-sfs-bg]:not([data-sfs-px], [data-sf-part], [data-sf-style="WholesaleTable"])', ['padding-inline: 1rem']));
  out.push(rule(':root [data-sf-style][data-sfs-max][data-sfs-align="center"]', ['margin-inline: auto']));
  out.push(rule(':root [data-sf-style][data-sfs-max][data-sfs-align="end"]', ['margin-inline-start: auto']));
  out.push(media('(max-width: 61.99em)', [rule(sel('hide', 'mobile'), ['display: none !important'], '  ')]));
  out.push(media('(min-width: 62em)', [rule(sel('hide', 'desktop'), ['display: none !important'], '  ')]));
  const phone: string[] = [];
  for (const key of ['padTop', 'padBottom', 'marginTop', 'marginBottom'] as const) {
    phone.push(rule(sel(key, 'lg'), [`${BLOCK_PROP[key]}: 1.5rem`], '  '));
    phone.push(rule(sel(key, 'xl'), [`${BLOCK_PROP[key]}: 2.5rem`], '  '));
  }
  for (const value of ['md', 'lg', 'xl']) phone.push(rule(sel('padX', value), ['padding-inline: 1rem'], '  '));
  phone.push(rule(sel('textSize', 'xl'), ['--sf-text-scale: 1.125'], '  '));
  phone.push(rule(':root [data-sfs-px] [data-sfs-px] [data-sfs-px]', ['padding-inline: 0'], '  '));
  out.push(media('(max-width: 47.99em)', phone));
  return out.join('');
}
