/** Editor-only notes for area `account`: where each line appears, in shopper words (Text panel). */
export default {
  'nav.orders': 'Account section tab, and the small label on the orders error and empty screens',
  'nav.loyalty': 'Account section tab, and the small label on the loyalty error screen',
  'nav.referrals': 'Account section tab, and the small label on the referrals error screen',
  'nav.profile': 'Account section tab, and the small label on the profile error screen',
  'nav.ariaLabel': 'Screen-reader name of the account section tabs',
  'layout.eyebrow': "Small label above the shopper's name at the top of every account page",
  'layout.standing': "Line under the shopper's name; {date} is when they joined and {orders} is their order count",
  'orders.count': 'Order count on the account header and above the order list',
  'orders.loadFailedTitle': 'Heading when the order history fails to load',
  'orders.loadFailedBody': 'Text under the heading when the order history fails to load',
  'orders.emptyTitle': 'Heading of the order history when the shopper has no orders',
  'orders.emptyBody': 'Text under the heading of an empty order history',
  'orders.title': 'Heading above the list of orders',
  'orders.balanceDue': 'Line on an order row with money still owed; {amount} is the amount',
  'orders.loadingMore': 'Label of the Load more button while the next page of orders loads',
  'orders.loadMore': 'Button at the end of the order list that shows older orders',
  'order.title': 'Small label above the heading when a single order fails to load or is not found, and the hidden page heading while it loads',
  'order.notFoundTitle': "Heading when the reference is not one of the signed-in customer's orders",
  'order.loadFailedTitle': 'Heading when one order fails to load',
  'order.notFoundBody': 'Text under the heading when an order cannot be found',
  'order.loadFailedBody': 'Text under the heading when one order fails to load',
  'order.allOrders': 'Button back to the order list from the order-not-found screen',
  'order.backToOrders': 'Link at the top of an order that goes back to the order list (a chevron is drawn before it)',
  'order.placed': 'Order date at the top of an order; {date} is the date',
  'order.collectFrom': 'Line under the order date when the order goes to a collection point; {name} is the point',
  'order.balanceDue': 'Banner on an order that still has money owed',
  'order.payHelp': 'Account order page: shown under the balance when the order cannot be paid online',
  'order.items': 'Heading of the items section of an order',
  'order.lines': 'Number of item lines, beside the Items heading',
  'order.payments': 'Heading of the payments section of an order',
  'order.parcels': 'Heading of the parcels section of an order',
  'order.parcelCount': 'Number of parcels, beside the Parcels heading',
  'order.parcelFallback': 'Name of a parcel that has no carrier name',
  'order.awaitingDispatch': 'Shown on a parcel with no tracking number and no dispatch date yet',
  'order.shippedFallback': 'Status of a parcel whose status is not one the shop recognises',
  'order.trackParcel': "Link to the carrier's tracking page for a parcel",
  'order.pay.eyebrow': 'Small heading of the payment card on an order that still has money owed',
  'order.pay.loading': 'Screen-reader text while the payment options of an unpaid order load',
  'order.pay.loadFailed': 'Shown in the payment card when the payment options could not be loaded; a Try again button sits beside it',
  'order.pay.rateLimited': 'Shown in the payment card instead of the line above when the shop said there were too many requests',
  'order.pay.updating': 'Payment card: shown for a moment when a payment has just landed and the order is catching up',
  'order.paymentReceived': 'Order page: said once, in a notification and to screen readers, when a payment arrives while the customer is looking',
  'order.address.delivery': 'Heading of the card showing where an order is being delivered',
  'order.address.collection': 'Heading of the card showing the collection point an order goes to',
  'order.address.viaCarrier': 'Line under the collection point name; {carrier} is the carrier that runs the point',
  'order.address.neutral': 'Heading of the address card on a cancelled or refunded order',
  'order.address.collecting': 'Line naming who collects the parcel, under the collection point address; {name} is the customer',
  'order.cancelledNote': 'Sentence under the heading of a cancelled order',
  'order.nothingCharged': 'Added after the cancelled sentence when no payment was taken',
  'order.refundedNote': 'Sentence under the heading of a refunded order',
  'order.paymentStatus.pending': 'Payment history: a payment started but not yet completed',
  'order.paymentStatus.completed': 'Payment history: a payment that went through',
  'order.paymentStatus.failed': 'Payment history: a payment that did not go through',
  'order.paymentStatus.cancelled': 'Payment history: a payment that was cancelled',
  'order.paymentStatus.expired': 'Payment history: a payment that ran out of time',
  'order.paymentStatus.refunded': 'Payment history: a payment that was paid back',
  'loyalty.redeemedToast': 'Pop-up after redeeming points; {credit} is the credit gained, {points} the new points balance, {balance} the new credit balance',
  'loyalty.redeemFailed': 'Pop-up when redeeming points fails',
  'loyalty.loadFailedTitle': 'Heading when the loyalty page fails to load',
  'loyalty.loadFailedBody': 'Text under the heading when the loyalty page fails to load',
  'loyalty.points': 'Unit label beside the big points balance',
  'loyalty.storeCredit': "Row label for the shopper's store credit balance",
  'loyalty.noPoints': 'Shown under the balance when the shopper has no points yet',
  'loyalty.redeemAria': 'Screen-reader name of the redeem section',
  'loyalty.redeemTitle': 'Heading of the redeem section',
  'loyalty.redeem': 'Redeem buttons',
  'loyalty.nothingToRedeem': 'Shown when the shop has no redemption options',
  'loyalty.cost': 'Points cost of a redemption option; {points} is a formatted number',
  'loyalty.worth': 'Credit value of a redemption option the shopper can afford; {credit} is money',
  'loyalty.pointsToGo': 'Shown on a redemption option the shopper cannot afford yet; {points} is the shortfall',
  'loyalty.confirmTitle': 'Title of the confirmation pop-up before redeeming',
  'loyalty.confirmBody': 'Text of the redemption confirmation; {reward} is the option name, {points} the cost, {credit} the credit gained',
  'loyalty.redeeming': 'Confirm button label while the redemption is being processed',
  'profile.loadFailedTitle': 'Heading when the profile page fails to load',
  'profile.loadFailedBody': 'Text under the heading when the profile page fails to load',
  'profile.detailsTitle': 'Heading of the profile details',
  'profile.name': "Profile row label for the shopper's name",
  'profile.nameNotSet': 'Profile value when the shopper has no name',
  'profile.memberSince': 'Profile row label for the join date',
  'profile.orders': 'Profile row label for the number of orders',
  'profile.totalSpend': 'Profile row label for what the shopper has spent',
  'profile.channelsAria': 'Screen-reader name of the sign-in channels section',
  'profile.channelsTitle': 'Heading of the list of sign-in channels',
  'profile.email': 'Sign-in channel name',
  'profile.channelLinked': 'Sign-in channel the shopper has linked; {channel} is Telegram, WhatsApp or Email',
  'profile.channelNotLinked': 'Sign-in channel the shopper has not linked; {channel} is Telegram, WhatsApp or Email',
  'profile.channelsNote': 'Text under the sign-in channels list',
  'profile.contactAria': 'Screen-reader name of the contact section',
  'profile.talkToUs': "Heading above the shop's chat links on the profile page",
  'profile.signingOut': 'Sign out button label while signing out',
  'profile.signOut': 'Button that signs the shopper out',
  'profile.botAria': 'Screen-reader name of the switch-to-classic-bot section',
  'profile.botTitle': 'Heading of the switch-to-classic-bot section (Telegram beta only)',
  'profile.botNote': 'Text explaining the switch to the classic Telegram bot',
  'profile.botSwitch': 'Button that starts the switch to the classic bot',
  'profile.botSwitching': 'Confirm button label while switching to the classic bot',
  'profile.botConfirm': 'Button that confirms the switch to the classic bot',
  'profile.botFailed': 'Message when switching to the classic bot fails',
  'referrals.referredToast': 'Pop-up after entering a referral code; {name} is the person who referred them',
  'referrals.loadFailedTitle': 'Heading when the referrals page fails to load',
  'referrals.loadFailedBody': 'Text under the heading when the referrals page fails to load',
  'referrals.yourCode': "Label above the shopper's own referral code",
  'referrals.copyAria': 'Screen-reader name of the Copy button; {code} is the referral code',
  'referrals.yourLink': "Label above the shopper's own referral link (browser only, not in the Telegram Mini App)",
  'referrals.copyLinkAria': 'Screen-reader name of the Copy button beside the referral link',
  'referrals.share': 'Button that opens the device share sheet with the invite',
  'referrals.shareNote': 'Text under the share buttons',
  'referrals.shareText': 'The invite message sent to a friend; {shop} is the shop name, {code} the referral code',
  'referrals.broughtInAria': 'Screen-reader name of the referral results section',
  'referrals.broughtInTitle': 'Heading above the referral counts',
  'referrals.peopleReferred': 'Label under the number of people the shopper has referred',
  'referrals.ordersEarned': 'Label under the number of referred orders that earned rewards',
  'referrals.referrerAria': 'Screen-reader name of the referred-by section',
  'referrals.referrerTitle': 'Heading of the referred-by section',
  'referrals.referredBy': 'Label before the name of the person who referred the shopper',
  'referrals.someone': 'Shown when the referrer has no name',
  'referrals.enterCodeNote': 'Text above the referral code field',
  'referrals.codeAria': 'Screen-reader name of the referral code field',
  'referrals.codePlaceholder': 'Placeholder in the referral code field',
  'referrals.checking': 'Apply button label while the referral code is checked',
  'referrals.apply': 'Button that submits the referral code',
  'referrals.codeFailed': 'Message when a referral code is rejected',
  'password.aria': 'Screen-reader name of the Password section of the profile page',
  'password.title': 'Heading of the Password section of the profile page',
  'password.setNote': 'Under the Password heading when the account has a password',
  'password.unsetNote': 'Under the Password heading when the account has no password yet',
  'password.signInWith': 'Label above the list of the email and phone the shopper signs in with',
  'password.emailRow': 'Row label for the sign-in email in the Password section',
  'password.phoneRow': 'Row label for the sign-in phone in the Password section',
  'password.verified': 'Marker beside a sign-in email or phone that has been confirmed',
  'password.unverified': 'Marker beside a sign-in email or phone that has not been confirmed',
  'password.sendVerification': 'Button that emails a confirmation link for the sign-in email',
  'password.sendingVerification': 'Label of that button while it sends',
  'password.verificationSent': 'Shown after the confirmation email was requested',
  'password.setCta': 'Button that opens the form to set a first password',
  'password.changeCta': 'Button that opens the form to change the password',
  'password.current': 'Label of the current-password field in the change-password form',
  'password.new': 'Label of the new-password field in the Password section',
  'password.identifierHint': 'Shown above the email-or-phone field when the account has neither (a Telegram-only account)',
  'password.save': 'Button that saves the password in the Password section',
  'password.saving': 'Label of that button while it saves',
  'password.saved': 'Shown after the password was saved',
} as const satisfies Record<string, string>;
