/** Editor-only notes for area `auth`: where each line appears, in shopper words (Text panel). */
export default {
  'modal.lede': 'Line under the heading of the sign-in pop-up',
  'page.title': 'Heading of the sign-in page; {name} is the shop name',
  'page.lede': 'Line under the heading of the sign-in page',
  'options.unavailableTitle': 'Heading shown when the shop has no sign-in method switched on',
  'options.unavailableBody': 'Shown under the heading when no sign-in method is on; {name} is the shop name',
  'options.signingIn': 'Note under the Telegram button while the sign-in is being checked',
  'options.emailOrPhone': 'Title of the email-or-phone sign-in card',
  'telegram.previewNote': 'Shown in the page builder where the Telegram sign-in button will be',
  'telegram.widgetMissing': 'Warning under the Telegram card when the Telegram sign-in button does not appear',
  'telegram.widgetFailed': 'Error under the Telegram button when the sign-in fails',
  'telegram.errorTitle': 'Heading when signing in inside the Telegram app fails',
  'telegram.errorBody': 'Under the Telegram sign-in error heading; {detail} is an optional reason in brackets, keep it at the end',
  'telegram.noAccount': 'Reason shown when Telegram sends no account details to the shop',
  'telegram.signInFailed': 'Reason shown when the Telegram app sign-in request fails',
  'login.basketFailed': 'Pop-up message when the basket cannot be merged into the account after signing in',
  'whatsapp.received': "WhatsApp sign-in, once the shopper's message has arrived",
  'whatsapp.expiredNote': 'WhatsApp sign-in, when the code has run out',
  'whatsapp.expiredBody': 'WhatsApp sign-in, under "That code expired"',
  'whatsapp.startAgain': 'Button to get a new WhatsApp code',
  'whatsapp.open': 'Button that opens WhatsApp with the sign-in message ready',
  'whatsapp.sendCodeTo': "Label above the sign-in code; {number} is the shop's WhatsApp number",
  'whatsapp.sendCodeToUs': 'Label above the sign-in code when the shop has no WhatsApp number to show',
  'whatsapp.copyCode': 'Screen-reader label of the Copy button; {code} is the sign-in code',
  'whatsapp.waiting': 'WhatsApp sign-in, while waiting for the shopper to send the code; a countdown follows',
  'whatsapp.intro': 'WhatsApp card, before the shopper starts',
  'whatsapp.starting': 'WhatsApp button label while the code is being created',
  'whatsapp.continue': 'WhatsApp card main button',
  'whatsapp.finishFailed': 'WhatsApp sign-in error when the last step fails',
  'whatsapp.startFailed': 'WhatsApp sign-in error when the code cannot be created',
  'password.invalid': 'Error under the sign-in form when the email/phone or the password is wrong',
  'password.wrongCurrent': 'Error under the current-password field in Account when the password typed there is wrong',
  'password.taken': 'Error when creating an account or adding a sign-in with an email or phone another account already uses',
  'password.banned': 'Error when a banned account tries to sign in or reset its password',
  'password.unavailable': 'Error when the shop has switched email/phone sign-in off while the shopper was using it',
  'password.tooShort': 'Error under a new-password field when it has fewer than 8 characters',
  'password.tooLong': 'Error under a new-password field when it is longer than the 72-byte limit',
  'password.phoneInvalid': 'Error under the phone field when the number cannot be turned into an international number',
  'password.show': 'Screen-reader name of the button that reveals what is typed in a password field',
  'password.hide': 'Screen-reader name of the button that hides a revealed password again',
  'password.kindAria': 'Screen-reader name of the Email / Phone switch above the sign-in fields',
  'password.byEmail': 'Email / Phone switch: the email option',
  'password.byPhone': 'Email / Phone switch: the phone option',
  'password.emailLabel': 'Label of the email field in the email-or-phone sign-in card',
  'password.passwordLabel': 'Label of the password field when signing in',
  'password.createLabel': 'Label of the password field when creating an account',
  'password.rule': 'Hint under a new-password field: the length rule',
  'password.submitSignIn': 'Main button of the email-or-phone sign-in form',
  'password.submitSignUp': 'Main button of the create-account form',
  'password.working': 'Main button label while the request is in flight',
  'password.toSignUp': 'Link in the sign-in form that switches to creating an account',
  'password.toSignIn': 'Link in the create-account form that switches back to signing in',
  'password.toForgot': 'Link under the sign-in password field that opens password reset',
  'password.backToSignIn': 'Link in the password reset panel that goes back to the sign-in form',
  'password.forgot.title': 'Heading of the password reset panel inside the sign-in card',
  'password.forgot.whatsappBody': 'Reset by WhatsApp: explains that the shopper messages the shop and gets a link in the chat',
  'password.forgot.whatsappCta': 'Reset by WhatsApp: the button that opens WhatsApp with the reset message ready',
  'password.forgot.emailBody': 'Reset by email: line above the email field',
  'password.forgot.send': 'Reset by email: the button that sends the link',
  'password.forgot.sent': 'Reset by email: shown after sending, whether or not the address has an account (deliberately neutral)',
  'password.forgot.noneBody': 'Shown in the reset panel when the shop has no way to send a reset link for the chosen email or phone',
  'reset.heading.title': 'Heading of the reset-password page',
  'reset.heading.titleSet': 'Heading of the reset-password page for someone who has no password yet',
  'reset.heading.lede': 'Line under the reset-password heading',
  'reset.form.checking': 'Shown while the reset link is being checked',
  'reset.form.label': 'Label of the new-password field on the reset-password page',
  'reset.form.submit': 'Button that saves the new password on the reset-password page',
  'reset.form.saving': 'Label of that button while it saves',
  'reset.form.unreachable': 'Shown when the reset link could not be checked because the shop could not be reached',
  'reset.expired.title': 'Heading of the reset-password page when the link is expired, used or invalid',
  'reset.expired.body': 'Under the expired heading; also covers a shopper who already used the link',
  'verifyEmail.heading.title': 'Heading of the confirm-your-email page',
  'verifyEmail.status.checking': 'Shown while the email link is being confirmed',
  'verifyEmail.status.doneTitle': 'Heading of the confirmation once the email link worked',
  'verifyEmail.status.doneBody': 'Line under the confirmed heading',
  'verifyEmail.status.invalidTitle': 'Heading when the email link is expired, already used or invalid',
  'verifyEmail.status.invalidBody': 'Line under the expired email-link heading',
  'verifyEmail.status.otherTitle': 'Heading when the email link belongs to a different account than the one signed in',
  'verifyEmail.status.otherBody': 'Line under the different-account heading',
  'verifyEmail.status.errorTitle': 'Heading when the confirmation could not be completed (connection or server problem)',
  'verifyEmail.status.toProfile': 'Link from the confirm-your-email page to the shopper’s profile',
  'access.eyebrow': 'Small heading on the screen shown to a signed-in customer who is not allowed into a private shop',
  'access.defaultMessage': 'Message on that screen when the shop owner has not written one of their own',
  'access.signInLede': 'Line under the heading of the sign-in page when the shop can only be viewed after signing in',
  'access.registrationClosed': 'Line on the sign-in page when the shop is not opening new accounts',
  'access.myOrders': 'Link on the private-shop screen to the customer’s own orders',
  'access.checkAgain': 'Button on the private-shop screen that checks whether the customer has been given access since',
  'access.signOut': 'Button on the private-shop screen that signs the customer out',
  'access.contactAriaLabel': 'Screen-reader name of the group of contact buttons on the private-shop screen',
} as const satisfies Record<string, string>;
