/** Editor-only notes for area `auth`: where each line appears, in shopper words (Text panel). */
export default {
  'modal.lede': 'Line under the heading of the sign-in pop-up',
  'page.title': 'Heading of the sign-in page; {name} is the shop name',
  'page.lede': 'Line under the heading of the sign-in page; shown only on the first screen, not on the later steps',
  'options.unavailableTitle': 'Heading shown when the shop has no sign-in method switched on',
  'options.unavailableBody': 'Shown under the heading when no sign-in method is on; {name} is the shop name',
  'options.signingIn': 'Note under the Telegram button while the sign-in is being checked',
  'options.or': 'Small word between the WhatsApp/Telegram buttons and the email-or-phone form on the sign-in screen',
  'telegram.continue': 'Label of the Telegram sign-in button',
  'telegram.previewNote': 'Shown in the page builder where the Telegram sign-in button will be',
  'telegram.widgetMissing': 'Warning under the Telegram sign-in button when it does not appear',
  'telegram.widgetFailed': 'Error under the Telegram button when the sign-in fails',
  'telegram.errorTitle': 'Heading when signing in inside the Telegram app fails',
  'telegram.errorBody': 'Under the Telegram sign-in error heading; {detail} is an optional reason in brackets, keep it at the end',
  'telegram.starting': 'Label of the Telegram sign-in button while it opens Telegram',
  'telegram.startFailed': 'Error under the Telegram button when it cannot open Telegram',
  'telegram.unavailable': 'Shown when Telegram sign-in is not set up on the server, under the button or on the return page',
  'telegram.callback.title': 'Heading of the page the shopper lands on when coming back from Telegram, while signing in',
  'telegram.callback.checking': 'Line under that heading while the sign-in is checked',
  'telegram.callback.errorTitle': 'Heading of that page when the sign-in did not work',
  'telegram.callback.expired': 'Shown after coming back from Telegram when the sign-in was started elsewhere or timed out',
  'telegram.callback.failed': 'Shown after coming back from Telegram when Telegram did not confirm the sign-in',
  'telegram.callback.cancelled': 'Shown after coming back from Telegram when the shopper turned the sign-in down',
  'telegram.callback.generic': 'Shown after coming back from Telegram for any other failure',
  'telegram.noAccount': 'Reason shown when Telegram sends no account details to the shop',
  'telegram.signInFailed': 'Reason shown when the Telegram app sign-in request fails',
  'login.basketFailed': 'Pop-up message when the basket cannot be merged into the account after signing in',
  'whatsapp.received': "WhatsApp sign-in, once the shopper's message has arrived",
  'whatsapp.expiredNote': 'WhatsApp sign-in, when the code has run out',
  'whatsapp.expiredBody': 'WhatsApp sign-in, under "That code expired"',
  'whatsapp.startAgain': 'Button to get a new WhatsApp code',
  'whatsapp.open': 'Button that opens WhatsApp with the sign-in message ready',
  'whatsapp.sendCodeTo': "Label above the sign-in code; {number} is the shop's WhatsApp number",
  'whatsapp.sendCodeToUs': 'Label above the sign-in code when the shop has no WhatsApp number to show',
  'whatsapp.copyCode': 'Screen-reader label of the Copy button; {code} is the sign-in code',
  'whatsapp.waiting': 'WhatsApp sign-in, while waiting for the shopper to send the code; a countdown follows',
  'whatsapp.back': 'Link shown while a WhatsApp code is waiting; goes back to the list of ways to sign in',
  'whatsapp.starting': 'WhatsApp button label while the code is being created',
  'whatsapp.continue': 'Label of the WhatsApp sign-in button',
  'whatsapp.finishFailed': 'WhatsApp sign-in error when the last step fails',
  'whatsapp.startFailed': 'WhatsApp sign-in error when the code cannot be created',
  'password.invalid': 'Error under the sign-in form when the email/phone or the password is wrong',
  'password.wrongCurrent': 'Error under the current-password field in Account when the password typed there is wrong',
  'password.taken': 'Error when creating an account or adding a sign-in with an email or phone another account already uses',
  'password.banned': 'Error when a banned account tries to sign in or reset its password',
  'password.unavailable': 'Error when the shop has switched email/phone sign-in off while the shopper was using it',
  'password.tooShort': 'Error under a new-password field when it has fewer than 8 characters',
  'password.tooLong': 'Error under a new-password field when it is longer than the 72-byte limit',
  'password.phoneInvalid': 'Error under the phone field when the number cannot be turned into an international number',
  'password.show': 'Screen-reader name of the button that reveals what is typed in a password field',
  'password.hide': 'Screen-reader name of the button that hides a revealed password again',
  'password.kindAria': 'Screen-reader name of the Email / Phone switch above the sign-in fields',
  'password.byEmail': 'Email / Phone switch: the email option',
  'password.byPhone': 'Email / Phone switch: the phone option',
  'password.emailLabel': 'Label of the email field in the email-or-phone sign-in form',
  'password.passwordLabel': 'Label of the password field when signing in',
  'password.createLabel': 'Label of the password field when creating an account',
  'password.rule': 'Hint under a new-password field: the length rule',
  'password.submitSignIn': 'Main button of the email-or-phone sign-in form',
  'password.signUpTitle': 'Heading of the create-account form',
  'password.submitSignUp': 'Main button of the create-account form',
  'password.working': 'Main button label while the request is in flight',
  'password.toSignUp': 'Link in the sign-in form that switches to creating an account',
  'password.toForgot': 'Link under the sign-in password field that opens password reset',
  'password.backToSignIn': 'Link at the top of the create-account and password reset panels that goes back to the sign-in form',
  'password.forgot.title': 'Heading of the password reset step',
  'password.forgot.whatsappBody': 'Reset by WhatsApp: explains that the shopper messages the shop and gets a link in the chat',
  'password.forgot.whatsappCta': 'Reset by WhatsApp: the button that opens WhatsApp with the reset message ready',
  'password.forgot.emailBody': 'Reset by email: line above the email field',
  'password.forgot.send': 'Reset by email: the button that sends the link',
  'password.forgot.sent': 'Reset by email: shown after sending, whether or not the address has an account (deliberately neutral)',
  'password.forgot.noneBody': 'Shown in the reset panel when the shop has no way to send a reset link for the chosen email or phone',
  'reset.heading.title': 'Heading of the reset-password page',
  'reset.heading.titleSet': 'Heading of the reset-password page for someone who has no password yet',
  'reset.heading.lede': 'Line under the reset-password heading',
  'reset.form.checking': 'Shown while the reset link is being checked',
  'reset.form.label': 'Label of the new-password field on the reset-password page',
  'reset.form.submit': 'Button that saves the new password on the reset-password page',
  'reset.form.saving': 'Label of that button while it saves',
  'reset.form.unreachable': 'Shown when the reset link could not be checked because the shop could not be reached',
  'reset.expired.title': 'Heading of the reset-password page when the link is expired, used or invalid',
  'reset.expired.body': 'Under the expired heading; also covers a shopper who already used the link',
  'verifyEmail.heading.title': 'Heading of the confirm-your-email page',
  'verifyEmail.status.checking': 'Shown while the email link is being confirmed',
  'verifyEmail.status.doneTitle': 'Heading of the confirmation once the email link worked',
  'verifyEmail.status.doneBody': 'Line under the confirmed heading',
  'verifyEmail.status.invalidTitle': 'Heading when the email link is expired, already used or invalid',
  'verifyEmail.status.invalidBody': 'Line under the expired email-link heading',
  'verifyEmail.status.otherTitle': 'Heading when the email link belongs to a different account than the one signed in',
  'verifyEmail.status.otherBody': 'Line under the different-account heading',
  'verifyEmail.status.errorTitle': 'Heading when the confirmation could not be completed (connection or server problem)',
  'verifyEmail.status.toProfile': 'Link from the confirm-your-email page to the shopper’s profile',
  'access.eyebrow': 'Small heading on the screen shown to a signed-in customer who is not allowed into a private shop',
  'access.defaultMessage': 'Message on that screen when the shop owner has not written one of their own',
  'access.signInLede': 'Line under the heading of the sign-in page when the shop can only be viewed after signing in',
  'access.registrationClosed': 'Line on the sign-in page when the shop is not opening new accounts',
  'access.myOrders': 'Link on the private-shop screen to the customer’s own orders',
  'access.checkAgain': 'Button on the private-shop screen that checks whether the customer has been given access since',
  'access.signOut': 'Button on the private-shop screen that signs the customer out',
  'access.contactAriaLabel': 'Screen-reader name of the group of contact buttons on the private-shop screen',
  'code.error.tooMany': 'Sign-in by code: shown when too many codes were asked for or tried (shop limits or the sending service’s)',
  'code.error.channelWhatsapp': 'Sign-in by code: shown when the code could not be sent to that number on WhatsApp',
  'code.error.channelSms': 'Sign-in by code: shown when the code could not be sent to that number as a text message',
  'code.error.cannotSwitch': 'Sign-in by code: shown when a waiting code cannot be sent another way to this number',
  'code.error.expired': 'Sign-in by code: shown when the code ran out of time; a button to send a new one follows',
  'code.error.incorrect': 'Sign-in by code: shown after a wrong code; {count} is how many tries are left',
  'code.error.incorrectNoCount': 'Sign-in by code: shown after a wrong code when the number of tries left is not known',
  'code.error.unavailable': 'Sign-in by code: shown when the shop’s code sending is switched off or down',
  'code.enter.label': 'Screen-reader name of the box where the 6-digit sign-in code is typed',
  'code.phone.country': 'Label of the country picker above the phone number when signing in with a phone',
  'code.phone.chooseCountry': 'First line of the country picker before a country is chosen',
  'code.phone.suggested': 'Heading over the shop’s own countries at the top of the country picker',
  'code.phone.allCountries': 'Heading over the rest of the countries in the country picker',
  'code.phone.number': 'Label of the phone number field when signing in with a phone',
  'code.enter.title': 'Heading of the screen where the 6-digit sign-in code is typed',
  'code.enter.body': 'Line under that heading; {to} is the hidden phone number or email, {channel} is one of the three words below',
  'code.channel.whatsapp': 'The word that fills {channel} when the code went by WhatsApp',
  'code.channel.sms': 'The word that fills {channel} when the code went as a text message',
  'code.channel.email': 'The word that fills {channel} when the code went by email',
  'code.resend': 'Link that sends the code again, once the wait is over',
  'code.resendIn': 'The same link while the wait is on; {time} counts down like 0:42',
  'code.switchSms': 'Link on the code screen that sends the code as a text message instead of WhatsApp',
  'code.switchWhatsapp': 'Link on the code screen that sends the code on WhatsApp instead of as a text message',
  'code.differentNumber': 'Link at the top of the code screen (phone) that goes back to typing the number',
  'code.differentEmail': 'Link at the top of the code screen (email) that goes back to typing the email',
  'code.sentAgain': 'Shown after the code was sent again or sent another way',
  'code.error.sendNew': 'Button shown when the code ran out of time or too many tries were used; asks for a new one',
  'code.phone.countryRequired': 'Shown under the country picker when a phone number was typed without choosing a country',
  'code.phone.intro': 'Short line under the heading of the phone step of the sign-in page',
  'code.email.intro': 'Short line under the heading of the email step of the sign-in page; shown only when the shop emails sign-in codes',
  'code.choose.phone': 'Label of the first big button on the sign-in page: signing in with a phone number',
  'code.choose.email': 'Label of the last big button on the sign-in page: signing in with an email',
  'code.choose.newHere': 'Small line under the sign-in buttons; hidden while the shop is not taking new customers',
  'code.back': 'Link at the top of the phone and email steps that goes back to the list of ways to sign in',
  'code.phone.title': 'Heading of the phone step of the sign-in page',
  'code.phone.sendWhatsapp': 'Button that sends the sign-in code by WhatsApp',
  'code.phone.sendSms': 'Button that sends the sign-in code as a text message',
  'code.phone.whatsappBody': 'Line on the phone step when the shopper signs in by messaging the shop on WhatsApp',
  'code.email.title': 'Heading of the email step of the sign-in page',
  'code.email.continue': 'Button on the email step',
  'code.password.title': 'Heading shown to someone whose account has a password, after they typed their email',
  'code.password.body': 'Line under that heading; {email} is the address they typed',
  'code.password.emailCode': 'Big button on the password screen that emails a sign-in code instead of asking for the password',
  'code.forgot.body': 'Line on the reset-password step when the shop can email a link; {email} is the address they typed',
} as const satisfies Record<string, string>;
