/** Editor-only notes for area `auth`: where each line appears, in shopper words (Text panel). */
export default {
  'modal.lede': 'Line under the heading of the sign-in pop-up',
  'page.title': 'Heading of the sign-in page; {name} is the shop name',
  'page.lede': 'Line under the heading of the sign-in page',
  'options.unavailableTitle': 'Heading shown when the shop has no sign-in method switched on',
  'options.unavailableBody': 'Shown under the heading when no sign-in method is on; {name} is the shop name',
  'options.signingIn': 'Note under the Telegram button while the sign-in is being checked',
  'options.soon': 'Inside the greyed-out email or phone sign-in card',
  'options.emailOrPhone': 'Title of the greyed-out email or phone sign-in card',
  'telegram.previewNote': 'Shown in the page builder where the Telegram sign-in button will be',
  'telegram.widgetMissing': 'Warning under the Telegram card when the Telegram sign-in button does not appear',
  'telegram.widgetFailed': 'Error under the Telegram button when the sign-in fails',
  'telegram.errorTitle': 'Heading when signing in inside the Telegram app fails',
  'telegram.errorBody': 'Under the Telegram sign-in error heading; {detail} is an optional reason in brackets, keep it at the end',
  'telegram.noAccount': 'Reason shown when Telegram sends no account details to the shop',
  'telegram.signInFailed': 'Reason shown when the Telegram app sign-in request fails',
  'login.basketFailed': 'Pop-up message when the basket cannot be merged into the account after signing in',
  'whatsapp.received': "WhatsApp sign-in, once the shopper's message has arrived",
  'whatsapp.expiredNote': 'WhatsApp sign-in, when the code has run out',
  'whatsapp.expiredBody': 'WhatsApp sign-in, under "That code expired"',
  'whatsapp.startAgain': 'Button to get a new WhatsApp code',
  'whatsapp.open': 'Button that opens WhatsApp with the sign-in message ready',
  'whatsapp.sendCodeTo': "Label above the sign-in code; {number} is the shop's WhatsApp number",
  'whatsapp.sendCodeToUs': 'Label above the sign-in code when the shop has no WhatsApp number to show',
  'whatsapp.copyCode': 'Screen-reader label of the Copy button; {code} is the sign-in code',
  'whatsapp.waiting': 'WhatsApp sign-in, while waiting for the shopper to send the code; a countdown follows',
  'whatsapp.intro': 'WhatsApp card, before the shopper starts',
  'whatsapp.starting': 'WhatsApp button label while the code is being created',
  'whatsapp.continue': 'WhatsApp card main button',
  'whatsapp.finishFailed': 'WhatsApp sign-in error when the last step fails',
  'whatsapp.startFailed': 'WhatsApp sign-in error when the code cannot be created',
  'password.invalid': 'Error under the sign-in form when the email/phone or the password is wrong',
  'password.wrongCurrent': 'Error under the current-password field in Account when the password typed there is wrong',
  'password.taken': 'Error when creating an account or adding a sign-in with an email or phone another account already uses',
  'password.banned': 'Error when a banned account tries to sign in or reset its password',
  'password.unavailable': 'Error when the shop has switched email/phone sign-in off while the shopper was using it',
  'password.tooShort': 'Error under a new-password field when it has fewer than 8 characters',
  'password.tooLong': 'Error under a new-password field when it is longer than the 72-byte limit',
  'password.phoneInvalid': 'Error under the phone field when the number cannot be turned into an international number',
} as const satisfies Record<string, string>;
