/** Editor-only notes for area `cart`: where each line appears, in shopper words (Text panel). */
export default {
  'summary.items': 'Item count in the cart drawer, cart page, cart summary, phone cart bar and checkout summary',
  'summary.mixedNotice': 'Notice above the cart total when the cart holds both in-stock and pre-order products',
  'summary.terms': 'Small print under the cart subtotal',
  'summary.held': 'Shown under the disabled Checkout button while a line is unavailable or breaks an order limit',
  'summary.checkout': 'Checkout button in the cart summary and the phone cart bar',
  'summary.keepShopping': 'Link under the cart summary back to the catalogue',
  'drawer.title': 'Heading of the slide-out cart, also its screen-reader label',
  'page.eyebrow': 'Small label above the cart page heading and above the empty-cart message',
  'page.title': 'Heading of the cart page',
  'empty.title': 'Heading of the empty cart, in the drawer and on the cart page',
  'empty.description': 'Text under the empty-cart heading',
  'line.removeButton': 'Text button that removes a line from the cart or from the trade-list order',
  'line.perUnit': 'Suffix after a unit price in the cart and the trade list',
  'line.priceUpdated': 'Chip on a cart line whose price the server changed',
  'line.quantityLabel': 'Screen-reader label of a quantity field; {name} is the product',
  'line.unavailable': 'Note on a cart line whose product has been withdrawn',
  'line.minimum': "Note on a cart line below its product's minimum order quantity",
  'line.maximum': "Note on a cart line above its product's maximum order quantity",
  'line.setTo': 'Button on a quantity-limit note that snaps the line to the limit',
  'bar.viewCartLabel': 'Screen-reader label of the phone cart bar link; {items} is the item count, {subtotal} the cart subtotal',
  'sync.signInAgain': 'Toast when the session has expired while saving the cart',
  'sync.updateFailed': 'Toast when saving the cart fails and the server gave no reason',
} as const satisfies Record<string, string>;
