/** Editor-only notes for area `catalog`: where each line appears, in shopper words (Text panel). */
export default {
  'search.placeholder': 'Placeholder of the header search box (a Search field block may set its own)',
  'search.ariaLabel': 'Screen-reader label of the header search box',
  'list.allProducts': 'Catalogue heading when no category is chosen, and the "show everything" row of the category index',
  'list.count': 'Product count under the catalogue heading',
  'list.matching': 'Count under the catalogue heading while the shopper is searching',
  'list.unit': 'Unit word beside the product tally on the menu layout',
  'list.of': 'Joins "shown" and "total" in the menu layout tally, e.g. 3 of 12',
  'list.eyebrowCatalogue': 'Small label above the catalogue empty and error messages',
  'list.eyebrowCategory': 'Small label above the "category not found" message',
  'list.eyebrowSearch': 'Small label above the "nothing matches" message',
  'list.loadFailedDetail': "Explanation under the \"couldn't load the products\" heading",
  'list.categoryMissingDetail': "Explanation under the \"category isn't here\" heading",
  'list.showAll': "Button on the \"category isn't here\" message",
  'list.noMatchesDetail': 'Advice under the "nothing matches" heading',
  'list.emptyCategoryDetail': 'Explanation under the "nothing stocked here yet" heading',
  'nav.categories': 'Heading and screen-reader name of the category index, chip row and filter sheet',
  'nav.all': 'First chip of the phone category row (shows every product)',
  'nav.allCategories': 'Button on the phone category row that opens the full category index',
  'filter.sub': "Line under the \"Categories\" heading of the menu layout's filter sheet",
  'group.other': 'Section name for products whose category has no name',
  'group.uncategorised': 'Section name for products with no category',
  'featured.ariaLabel': 'Screen-reader label of a Featured products block that has no title',
} as const satisfies Record<string, string>;
