/** Editor-only notes for area `checkout`: where each line appears, in shopper words (Text panel). */
export default {
  'errors.required': 'Under a checkout (or verification) field left empty',
  'errors.paymentMissing': 'Checkout payment step, when Continue is pressed with no method chosen',
  'errors.emailInvalid': 'Under the checkout email field, when the address is not a valid email',
  'errors.contactMissing': 'Under the guest checkout email field, when neither email nor phone is filled in',
  'errors.countryMissing': 'Under the checkout country picker, when no country is chosen',
  'errors.shippingMissing': 'Checkout delivery step, when Continue is pressed with no delivery option chosen',
  'errors.pointMissing': 'Shown on the address step when collection is chosen but no point is picked',
  'errors.coinMissing': 'Checkout payment step, when crypto is chosen without a coin and network',
  'errors.stillPricing': 'Checkout delivery and payment steps, when Continue is pressed before the order is priced',
  'errors.shippingStale': 'Checkout delivery step, when the chosen delivery option has been withdrawn',
  'errors.methodStale': 'Checkout payment step, when the chosen payment method has been withdrawn',
  'errors.comboStale': 'Checkout payment step, when the chosen coin and network have been withdrawn',
  'errors.unknownCode': 'Under the coupon field, when the code entered does not exist',
  'errors.verifyBrowser': 'Top of guest checkout, when the invisible bot check fails (with a Try again button)',
  'errors.verifyFailed': 'Guest checkout, when the invisible bot check fails or times out',
  'errors.placeFailed': 'Top of the checkout, when placing the order fails without a reason from the shop',
  'errors.inProgress': 'Pop-up message when the order is placed twice at the same time',
  'page.eyebrow': 'Small label above the checkout heading and the checkout notices',
  'page.title': 'Checkout page heading for a signed-in shopper',
  'page.guestTitle': 'Checkout page heading for a shopper who is not signed in',
  'page.guestUnavailableTitle': 'Checkout page heading when guest checkout is switched on but cannot run',
  'page.guestUnavailableBody': 'Line under "Guest checkout isn\'t available right now"',
  'page.emptyTitle': 'Checkout page heading when the cart is empty',
  'page.emptyBody': 'Line under "There\'s nothing to check out"',
  'page.verifying': 'Guest checkout, while the invisible bot check runs',
  'page.terms': 'Small print under the Place order button on the review step',
  'steps.contact': 'Name of the first checkout step, in the step bar and on the review step',
  'steps.contactTitle': 'Heading of the first checkout step',
  'steps.address': 'Name of the address step in the checkout step bar',
  'steps.addressTitle': 'Heading of the address step, and its box on the review step',
  'steps.shipping': 'Name of the delivery step, in the step bar and on the review step',
  'steps.shippingTitle': 'Heading of the delivery step',
  'steps.payment': 'Name of the payment step, in the step bar and on the review step',
  'steps.paymentTitle': 'Heading of the payment step',
  'steps.review': 'Name of the last checkout step in the step bar',
  'steps.reviewTitle': 'Heading of the last checkout step',
  'steps.count': 'Above each checkout step heading; {current} is the step number, {total} the number of steps',
  'actions.continue': 'Checkout button that moves on to the next step',
  'actions.back': 'Checkout button that goes back one step',
  'actions.placing': 'Place order button while the order is being placed',
  'actions.placeOrder': 'Button on the review step when there is nothing to pay',
  'actions.placeOrderTotal': 'Button on the review step; {total} is the amount to pay',
  'address.blurb': 'Line at the top of the address step',
  'address.line1': 'Address step field label',
  'address.line2': 'Address step field label (optional field)',
  'address.line3': 'Address step field label (optional field)',
  'address.city': 'City field label for countries without their own wording',
  'address.zip': 'Postal code field label for countries without their own wording',
  'address.county': 'State or region field label for countries without their own wording (optional field)',
  'address.townCity': 'City field label when delivering to the UK (including the Isle of Man, Jersey and Guernsey) or Ireland',
  'address.countyPlain': 'County field label when delivering to the UK (including the Isle of Man, Jersey and Guernsey) or Ireland (optional field)',
  'address.postcode': 'Postal code field label when delivering to the UK (including the Isle of Man, Jersey and Guernsey) or Australia',
  'address.eircode': 'Postal code field label when delivering to Ireland',
  'address.state': 'State field label when delivering to the US or Australia (optional field)',
  'address.zipCode': 'Postal code field label when delivering to the US',
  'address.province': 'Province field label when delivering to Canada (optional field)',
  'address.suburb': 'City field label when delivering to Australia',
  'address.country': 'Label of the country picker',
  'address.chooseCountry': 'First, empty choice in the country picker',
  'address.deliverTo': 'Label of the home / collection switch on the address step',
  'address.methodHome': 'Home / collection switch: the home delivery option',
  'address.methodCollection': 'Home / collection switch: the collection point option',
  'address.collectionOnly': 'Address step note when the country delivers only to collection points; {country} is the country name',
  'address.pointPostcode': 'Label of the postcode box in the collection point search',
  'address.pointSearch': 'Button that searches for collection points near the postcode',
  'address.pointPrompt': 'Line under the collection point search before any search',
  'address.pointSearching': 'Status line while collection points are loading',
  'address.pointEmpty': 'Status line when a postcode has no collection points',
  'address.pointFailed': 'Status line when collection points could not be loaded',
  'address.pointBusy': 'Status line when the shopper has searched too often',
  'address.pointList': 'Screen reader name of the list of collection points found',
  'address.pointChosen': 'Heading over the collection point the shopper has chosen',
  'address.pointChange': 'Button that reopens the collection point search',
  'address.pointDistance': 'Distance to a collection point; {km} is a number with one decimal',
  'contact.blurbEmail': 'Line at the top of the contact step when the shop asks for an email',
  'contact.blurbNoEmail': 'Line at the top of the contact step when the shop does not ask for an email',
  'contact.firstName': 'Contact step field label',
  'contact.surname': 'Contact step field label',
  'contact.email': 'Contact step field label',
  'contact.haveAccount': 'Guest checkout contact step; {signIn} is the Sign in link',
  'field.optional': 'Small tag beside an optional checkout field label',
  'phone.codeAriaLabel': 'Screen-reader label of the dial-code picker',
  'phone.code': 'Label of the dial-code picker, and its empty choice',
  'phone.label': 'Contact step phone field label',
  'phone.hint': 'Small line under the phone field',
  'coupon.codeLabel': 'Label of the coupon field on the delivery step',
  'coupon.placeholder': 'Placeholder inside the coupon field',
  'coupon.checking': 'Coupon Apply button while the code is checked',
  'coupon.apply': 'Coupon field button',
  'coupon.discountLabel': 'Label over a coupon code that is on the order (or was turned down)',
  'coupon.notApplied': 'Beside a coupon code the shop turned down without a reason',
  'coupon.remove': 'Button that takes a coupon code off the order',
  'coupon.autoApplied': 'Beside a discount the shop applied on its own',
  'coupon.useAnother': 'Button to enter a different code over an automatic discount',
  'crypto.coins': 'Group heading in the crypto coin and network picker',
  'crypto.stablecoins': 'Group heading in the crypto coin and network picker',
  'quote.pricing': 'Delivery and payment steps, while the order is being priced',
  'shipping.heading': 'Heading over the delivery options',
  'shipping.unserviceable': 'Delivery step, when there are no delivery options for the address; {country} is the country name',
  'shipping.thatCountry': 'Stands in for {country} in "We can’t ship to {country} yet" when the country has no name',
  'shipping.free': 'Price of a free delivery option, and the shipping row of the order summary',
  'payment.useStoreCredit': 'Payment step checkbox for a signed-in shopper with a balance',
  'payment.creditAvailable': 'Beside "Use store credit"; {amount} is the balance',
  'payment.allCovered': 'Payment step, when store credit pays for the whole order',
  'payment.noMethods': 'Payment step, when the shop offers no way to pay',
  'payment.methodHeading': 'Heading over the payment methods',
  'payment.fee': 'Beside a payment method\'s fee rate when the method has no fee name of its own',
  'payment.offlineNote': 'Payment step, under a bank-transfer style method',
  'review.blurb': 'Line at the top of the review step',
  'review.change': 'Button on each review-step box that goes back to that step',
  'review.notChosen': 'Review step, for a delivery option or payment method not yet chosen',
  'review.notes': 'Review step notes field label',
  'review.notesPlaceholder': 'Placeholder inside the order notes field',
  'summary.ariaLabel': 'Order summary beside the checkout: its screen-reader name, and the phone toggle while closed',
  'summary.hide': 'Phone toggle of the order summary while open',
  'summary.heading': 'Heading of the order summary beside the checkout',
  'summary.bulk': 'Tag on a summary line priced at a bulk tier',
  'summary.discountCode': 'Order summary discount row; {code} is the coupon code',
  'summary.nothingToPay': 'Order summary\'s final figure label when store credit covers it',
  'summary.toPay': 'Order summary\'s final figure label once a payment method is chosen',
  'summary.amountDue': 'Order summary row and final figure label before a payment method is chosen',
  'summary.creditCovers': 'Under the order summary when store credit pays for everything',
  'summary.pending': 'Under the order summary before an address is entered',
} as const satisfies Record<string, string>;
