/** Editor-only notes for area `common`: where each line appears, in shopper words (Text panel). */
export default {
  'actions.tryAgain': 'Retry button on error screens across the shop',
  'actions.copy': 'Copy-to-clipboard button',
  'actions.copied': 'Copy button, just after copying',
  'actions.browseCatalogue': 'Button on the empty cart, empty checkout and empty order history',
  'actions.backToShop': 'Link back to the catalogue on order, payment and verification pages',
  'actions.close': 'Screen-reader label of the close (×) button on drawers and sheets',
  'actions.signIn': 'Sign-in button, and the header account button when signed out',
  'actions.cancel': 'Button that backs out of a confirmation (loyalty redemption, switching to the classic bot)',
  'status.loading': 'Screen-reader label while a page or list loads',
  'status.checking': 'Button label while a code, reference or transaction is being checked',
  'product.preorder': 'Tag on pre-order products, cart lines and order items',
  'product.outOfStock': 'Sold-out product: the add-to-cart button label, and the note on a cart line',
  'shipment.parcelOf': 'Heading of each parcel card when an order has several, on the order and tracking pages',
  'shipment.trackingNumber': 'Label of the copyable tracking number on a parcel card (order and tracking pages)',
  'shipment.inTransit': 'Parcel status "on its way", on the order and tracking pages',
  'dates.delivered': 'When the order or a parcel was delivered, on the order and tracking pages; {date} is the date',
  'qty.fewer': 'Screen-reader label of the − quantity button; {name} is the product',
  'qty.more': 'Screen-reader label of the + quantity button; {name} is the product',
  'qty.remove': 'Screen-reader label of a line\'s remove button; {name} is the product',
  'totals.subtotal': 'Row label in the cart, checkout, order and account totals',
  'totals.total': 'Row label for the order total',
  'totals.discount': 'Row label for a discount in order totals',
  'totals.shipping': 'Row label for shipping in order totals',
  'totals.paymentFee': 'Row label for a payment-method fee',
  'totals.storeCredit': 'Row label for store credit applied or held',
  'nav.yourAccount': 'Header account button when signed in, and the account page heading fallback',
  'list.loadFailed': 'Catalogue and trade list, when the product list fails to load',
  'list.categoryMissing': 'Catalogue and trade list, for an unknown category link',
  'list.noMatches': 'Catalogue and trade list, when a search finds nothing',
  'list.clearSearch': 'Button under "Nothing matches"',
  'list.emptyCategory': 'Catalogue and trade list, for a category with no products',
  'contact.whatsapp': 'Contact-link and sign-in channel name',
  'contact.telegram': 'Contact-link and sign-in channel name',
  'video.title': 'Screen-reader name of an embedded video that has no title of its own',
} as const satisfies Record<string, string>;
