/** Editor-only notes for area `order`: where each line appears, in shopper words (Text panel). */
export default {
  'status.pending': 'Status name of a new order in order lists and on the tracking page',
  'status.confirmed': 'Status name of a confirmed order',
  'status.processing': 'Status name while an order is packed',
  'status.partiallyShipped': 'Status name when some parcels have shipped',
  'status.shipped': 'Status name once shipped',
  'status.delivered': 'Status name once delivered',
  'status.cancelled': 'Status name of a cancelled order',
  'status.refunded': 'Status name of a refunded order',
  'link.eyebrow': "Small line above the payment-return pages' missing-reference screen",
  'cancel.action': 'Button that starts cancelling an unpaid order',
  'cancel.confirmTitle': 'Heading of the cancel confirmation; {reference} is the order reference',
  'cancel.confirmBody': 'Cancel confirmation: what cancelling does',
  'cancel.confirm': 'Cancel confirmation: the button that cancels the order',
  'cancel.keep': 'Cancel confirmation: the button that backs out',
  'cancel.working': 'Cancel confirmation: confirm button while the request runs',
  'cancel.done': 'Notification after an order was cancelled; {reference} is the order reference',
  'cancel.contact': 'Shown instead of the cancel button when a payment may be on its way; the shop support links follow',
  'cancel.refusedPaid': 'Shown when cancelling is refused because the order was paid meanwhile',
  'cancel.refusedInFlight': 'Shown when cancelling is refused because a bank transfer or crypto payment may be on its way',
  'cancel.refusedGone': 'Shown when cancelling is refused because the order is no longer pending',
  'cancel.failed': 'Shown when cancelling failed for any other reason; the customer can retry',
  'prompt.title': 'Heading of the pop-up that asks a returning customer about an unpaid order',
  'prompt.body': 'Pop-up sentence naming the unpaid order; {reference} is the order reference',
  'prompt.amount': 'Pop-up label beside the amount still to pay',
  'prompt.review': 'Pop-up button that opens the order page, where the customer pays or cancels',
  'prompt.later': 'Pop-up button that hides it until the site is next loaded',
  'prompt.more': 'Pop-up link to the order list, shown when there is more than one unpaid order',
  'shipment.status.shipped': 'Parcel status pill',
  'shipment.status.delivered': 'Parcel status pill',
  'shipment.status.returned': 'Parcel status pill',
  'copy.copyNamed': 'Screen-reader label of a Copy button; {name} is what it copies, in lower case',
  'copy.copiedNamed': 'Screen-reader label of a Copy button just after copying; {name} is what was copied',
  'payment.ariaLabel': 'Screen-reader label of the payment card',
  'payment.chooseTitle': 'Instruction above the list of ways to pay',
  'payment.finishTitle': 'Payment card heading while a hosted checkout is open',
  'payment.payingWith': 'Line under "Finish your payment" naming the method the customer chose; {method} is the shop’s own name for it',
  'payment.hostedLead': 'Reassurance line under "Finish your payment"',
  'payment.openCheckout': 'Button that opens the hosted checkout in a new tab; the customer taps it when ready to pay',
  'payment.hostedNote': 'Note under the hosted-checkout button',
  'payment.pendingTitle': 'Heading of the card for a payment arranged with the shop',
  'payment.pendingNote': 'Text of the card for a payment arranged with the shop',
  'payment.deadline': 'Deadline above the ways to pay; {when} is the date and time, shown in bold',
  'payment.changeMethod': 'Button that opens the list to switch payment method',
  'payment.keepMethod': 'The same button while the switch list is open',
  'method.loading': 'While the payment methods load',
  'method.none': 'When no payment method can be used on the order page',
  'method.opening': 'Payment method row while its hosted checkout opens',
  'method.discountNote': 'Second line of a payment option that is cheaper than the amount due; {rate} is the percentage',
  'method.savesNote': 'Second line of a cheaper payment option when the shop gives no percentage; {amount} is the saving',
  'method.feeNote': "Second line of a payment option that adds a fee; {fee} is the fee in the shop's currency",
  'method.feeLabelNote': "Second line of a payment option that adds a fee the shop has named (for example 'Card fee'); {label} is that name, {fee} the amount",
  'method.preparing': 'Crypto pay button while the payment is created',
  'method.payWith': 'Crypto pay button; {coin} is the coin and network',
  'method.chooseCoin': 'Crypto pay button before a coin is picked',
  'method.coinBlurb': 'Note under the crypto pay button',
  'method.transferHead': 'Heading of the bank-transfer details; {method} is the method name',
  'method.paymentReference': 'Label of the copyable order reference in bank-transfer details',
  'method.transferBlurb': 'Note under the bank-transfer details',
  'method.noDetails': 'When a bank transfer has no details to show; {reference} is the order ID',
  'crypto.label': 'Crypto payment card heading line once sent, and its screen-reader label',
  'crypto.pillChecking': 'Crypto card status pill while the transaction is checked',
  'crypto.pillConfirmed': 'Crypto card status pill once confirmed',
  'crypto.pillAttention': 'Crypto card status pill when the shop is reviewing it',
  'crypto.titleChecking': 'Crypto card heading while the transaction is checked',
  'crypto.titleConfirmed': 'Crypto card heading once confirmed',
  'crypto.titleAttention': 'Crypto card heading when the shop is reviewing it',
  'crypto.payTitle': 'Crypto card heading before paying; {coin} is the coin',
  'crypto.network': "Line under the crypto card heading; {network} is the network, {fiat} the amount in the shop's currency",
  'crypto.amountToSend': 'Label of the copyable amount (crypto and bank transfer)',
  'crypto.addressLabel': 'Label of the copyable deposit address',
  'crypto.warning': 'Warning on the crypto card before paying; {network} is the network',
  'crypto.txidLabel': 'Label of the transaction ID field and of the submitted ID',
  'crypto.txidBlurb': 'Help under the transaction ID label',
  'crypto.txidPlaceholder': 'Placeholder in the transaction ID field',
  'crypto.sending': 'Submit button while the transaction ID is sent',
  'crypto.submit': 'Button that sends the transaction ID',
  'crypto.checkingNote': 'Note while the transaction is checked',
  'crypto.receivedInFull': 'Note once the crypto payment is confirmed',
  'crypto.attentionNote': 'Note when the shop is reviewing the crypto payment',
  'errors.loadMethods': 'When the payment methods fail to load',
  'errors.methodUnavailable': 'When choosing a payment method fails',
  'errors.txidRejected': 'When a submitted transaction ID is refused',
  'chat.payRequest': 'Chat message prefilled by "pay via chat" links; {reference} is the order ID',
  'chat.inquiry': 'Chat message prefilled after a successful payment; {reference} is the order ID',
} as const satisfies Record<string, string>;
