/** Editor-only notes for area `order`: where each line appears, in shopper words (Text panel). */
export default {
  'documentTitle': 'Browser tab title on the order page; {reference} is the order ID, {shop} the shop name',
  'hero.ariaLabel': 'Screen-reader label of the order page\'s top section',
  'hero.eyebrow': 'Small line above the order page headline (every state but delivered)',
  'hero.deliveredEyebrow': 'Small line above the order page headline once delivered',
  'hero.pendingHeadline': 'Order page headline for a new order',
  'hero.pendingDetail': 'Sentence under the headline for a new order',
  'hero.confirmedHeadline': 'Order page headline for a confirmed order',
  'hero.confirmedDetail': 'Sentence under the headline for a confirmed order',
  'hero.processingHeadline': 'Order page headline while the order is packed',
  'hero.processingDetail': 'Sentence under the headline while the order is packed',
  'hero.partiallyShippedHeadline': 'Order page headline when some parcels have shipped',
  'hero.partiallyShippedDetail': 'Sentence under the headline when some parcels have shipped',
  'hero.shippedHeadline': 'Order page headline once shipped',
  'hero.shippedDetail': 'Sentence under the headline once shipped',
  'hero.deliveredHeadline': 'Order page headline once delivered',
  'hero.deliveredDetail': 'Sentence under the headline once delivered',
  'hero.cancelledHeadline': 'Order page headline for a cancelled order',
  'hero.cancelledDetail': 'Sentence under the headline for a cancelled order',
  'hero.refundedHeadline': 'Order page headline for a refunded order',
  'hero.refundedDetail': 'Sentence under the headline for a refunded order',
  'hero.preorderFlag': 'Flag under the headline when the order has pre-order items',
  'hero.cancelledNotice': 'Note under the headline of a cancelled order',
  'hero.refundedNotice': 'Note under the headline of a refunded order',
  'dates.placed': 'When the order was placed; {date} is the date',
  'dates.shipped': 'When a parcel shipped; {date} is the date',
  'steps.ariaLabel': 'Screen-reader label of the four-step order progress',
  'steps.received': 'First step of the order progress',
  'steps.confirmed': 'Second step of the order progress',
  'steps.shipped': 'Third step of the order progress',
  'steps.delivered': 'Last step of the order progress',
  'steps.partial': 'Marker on the Shipped step when only some items have shipped',
  'status.pending': 'Status name of a new order in order lists and on the tracking page',
  'status.confirmed': 'Status name of a confirmed order',
  'status.processing': 'Status name while an order is packed',
  'status.partiallyShipped': 'Status name when some parcels have shipped',
  'status.shipped': 'Status name once shipped',
  'status.delivered': 'Status name once delivered',
  'status.cancelled': 'Status name of a cancelled order',
  'status.refunded': 'Status name of a refunded order',
  'screens.loading': 'Screen-reader label while the order page loads',
  'link.eyebrow': 'Small line above the "link isn\'t valid" and "reference missing" screens',
  'screens.invalidTitle': 'Heading when the order link is broken or expired',
  'screens.invalidDescription': 'Text when the order link is broken or expired',
  'screens.networkEyebrow': 'Small line above the "couldn\'t load your order" screen',
  'screens.networkTitle': 'Heading when the order page can\'t reach the shop',
  'screens.networkDescription': 'Text when the order page can\'t reach the shop',
  'footer.reference': 'Order ID at the foot of the order page',
  'footer.questions': 'Line above the chat links at the foot of the order page',
  'items.title': 'Heading of the ordered-items card (capital I)',
  'items.delivery': 'Totals row for the delivery charge on the order page',
  'items.free': 'Delivery amount when delivery costs nothing',
  'items.paymentDiscount': 'Totals row when the payment method gives a discount',
  'items.tax': 'Totals row for tax',
  'address.title': 'Heading of the delivery-address card',
  'address.collectFrom': 'Delivery-address card: label above the name of the collection point an order goes to',
  'cancel.action': 'Button that starts cancelling an unpaid order',
  'cancel.confirmTitle': 'Heading of the cancel confirmation; {reference} is the order reference',
  'cancel.confirmBody': 'Cancel confirmation: what cancelling does',
  'cancel.confirm': 'Cancel confirmation: the button that cancels the order',
  'cancel.keep': 'Cancel confirmation: the button that backs out',
  'cancel.working': 'Cancel confirmation: confirm button while the request runs',
  'cancel.done': 'Notification after an order was cancelled; {reference} is the order reference',
  'cancel.contact': 'Shown instead of the cancel button when a payment may be on its way; the shop support links follow',
  'cancel.refusedPaid': 'Shown when cancelling is refused because the order was paid meanwhile',
  'cancel.refusedInFlight': 'Shown when cancelling is refused because a bank transfer or crypto payment may be on its way',
  'cancel.refusedGone': 'Shown when cancelling is refused because the order is no longer pending',
  'cancel.failed': 'Shown when cancelling failed for any other reason; the customer can retry',
  'shipment.parcel': 'Heading of the parcel card when there is one parcel',
  'shipment.untitled': 'Parcel card title when the carrier is unknown',
  'shipment.track': 'Link to the carrier\'s tracking page',
  'shipment.status.shipped': 'Parcel status pill',
  'shipment.status.delivered': 'Parcel status pill',
  'shipment.status.returned': 'Parcel status pill',
  'copy.copyNamed': 'Screen-reader label of a Copy button; {name} is what it copies, in lower case',
  'copy.copiedNamed': 'Screen-reader label of a Copy button just after copying; {name} is what was copied',
  'payment.ariaLabel': 'Screen-reader label of the payment card',
  'payment.required': 'Small line above the payment card while money is owed',
  'payment.chooseHowToPay': 'Payment card heading; {total} is the amount owed',
  'payment.finishTitle': 'Payment card heading while a hosted checkout is open',
  'payment.hostedFigure': 'Line under "Finish your payment"; {total} is the amount',
  'payment.awaiting': 'Status pill on a payment card waiting for money',
  'payment.openCheckout': 'Button that opens the hosted checkout',
  'payment.hostedNote': 'Note under the hosted-checkout button',
  'payment.pendingEyebrow': 'Small line above the card for a payment arranged with the shop',
  'payment.pendingTitle': 'Heading of the card for a payment arranged with the shop',
  'payment.pendingNote': 'Text of the card for a payment arranged with the shop',
  'payment.deadline': 'Deadline above the payment card; {when} is the date and time',
  'payment.changeMethod': 'Button that opens the list to switch payment method',
  'payment.keepMethod': 'The same button while the switch list is open',
  'method.loading': 'While the payment methods load',
  'method.none': 'When no payment method can be used on the order page',
  'method.opening': 'Payment method row while its hosted checkout opens',
  'method.card': 'Name of the card payment option',
  'method.crypto': 'Name of the crypto payment option',
  'method.withDiscount': 'Payment option with a discount; {method} is its name, {rate} the percentage',
  'method.withFee': 'Payment option with a fee; {method} is its name, {rate} the percentage',
  'method.preparing': 'Crypto pay button while the payment is created',
  'method.payWith': 'Crypto pay button; {coin} is the coin and network',
  'method.chooseCoin': 'Crypto pay button before a coin is picked',
  'method.coinBlurb': 'Note under the crypto pay button',
  'method.transferHead': 'Heading of the bank-transfer details; {method} is the method name',
  'method.paymentReference': 'Label of the copyable order reference in bank-transfer details',
  'method.transferBlurb': 'Note under the bank-transfer details',
  'method.noDetails': 'When a bank transfer has no details to show; {reference} is the order ID',
  'crypto.label': 'Crypto payment card heading line once sent, and its screen-reader label',
  'crypto.pillChecking': 'Crypto card status pill while the transaction is checked',
  'crypto.pillConfirmed': 'Crypto card status pill once confirmed',
  'crypto.pillAttention': 'Crypto card status pill when the shop is reviewing it',
  'crypto.titleChecking': 'Crypto card heading while the transaction is checked',
  'crypto.titleConfirmed': 'Crypto card heading once confirmed',
  'crypto.titleAttention': 'Crypto card heading when the shop is reviewing it',
  'crypto.sendTitle': 'Crypto card heading before paying; {amount} and {coin} are the exact sum',
  'crypto.figure': 'Line under the crypto card heading; {fiat} is the amount in the shop\'s currency',
  'crypto.amountToSend': 'Label of the copyable amount (crypto and bank transfer)',
  'crypto.addressLabel': 'Label of the copyable deposit address',
  'crypto.sendExactly': 'Warning on the crypto card before paying',
  'crypto.txidLabel': 'Label of the transaction ID field and of the submitted ID',
  'crypto.txidBlurb': 'Help under the transaction ID label',
  'crypto.txidPlaceholder': 'Placeholder in the transaction ID field',
  'crypto.sending': 'Submit button while the transaction ID is sent',
  'crypto.submit': 'Button that sends the transaction ID',
  'crypto.checkingNote': 'Note while the transaction is checked',
  'crypto.receivedInFull': 'Note once the crypto payment is confirmed',
  'crypto.attentionNote': 'Note when the shop is reviewing the crypto payment',
  'errors.loadMethods': 'When the payment methods fail to load',
  'errors.methodUnavailable': 'When choosing a payment method fails',
  'errors.txidRejected': 'When a submitted transaction ID is refused',
  'chat.payRequest': 'Chat message prefilled by "pay via chat" links; {reference} is the order ID',
  'chat.inquiry': 'Chat message prefilled after a successful payment; {reference} is the order ID',
} as const satisfies Record<string, string>;
