/** Editor-only notes for area `product`: where each line appears, in shopper words (Text panel). */
export default {
  'stock.in': 'Stock chip on product cards and pages',
  'stock.low': 'Stock chip when stock is low',
  'stock.out': 'Stock chip when sold out',
  'limit.min': 'Minimum order quantity flag on product cards, rows and pages',
  'add.verb': "Start of the add-to-cart button label (\"Add 2 · $10.00\") and of a row's screen-reader label",
  'add.unavailable': "Add-to-cart button label for a product that can't be ordered",
  'add.added': 'Add-to-cart button label for a moment after adding',
  'add.another': 'Add-to-cart button label once a product has been added',
  'add.labelWithName': 'Screen-reader label of an icon-only add button: its label, then the product name',
  'add.ariaLabel': "Screen-reader label of a product row's quick-add button",
  'row.unavailable': "Screen-reader label of a product row's add button when the product can't be ordered",
  'row.outOfStock': "Screen-reader label of a product row's add button when sold out",
  'detail.breadcrumb': 'Screen-reader name of the trail above a product page',
  'detail.shop': 'First step of the breadcrumb on a product page (back to the catalogue)',
  'detail.preorderShips': 'Pre-order flag on a product page when a ship date is set',
  'detail.product': "Small label above the \"product not found\" message, and the product sheet's fallback title",
  'detail.notFoundTitle': "Heading when a product page can't be loaded",
  'detail.notFoundDetail': "Explanation under the \"can't find that product\" heading",
  'detail.browse': "Button on the \"can't find that product\" message",
  'bulk.heading': 'Heading of the quantity price ladder on a product',
  'bulk.quantity': 'Column heading of the quantity price ladder',
  'bulk.unitPrice': 'Column heading of the quantity price ladder',
  'bulk.saving': 'Column heading of the quantity price ladder',
  'provenance.heading': "Heading above a product's provenance note",
  'coa.heading': "Heading above a product's lab report (certificate of analysis)",
  'coa.lab': 'Label for the lab that tested the product, in the lab report block',
  'coa.sample': 'Label for the name of the tested sample, in the lab report block',
  'coa.amount': 'Label for the tested amount in mg, in the lab report block',
  'coa.purity': 'Label for the purity percentage, in the lab report block',
  'coa.batch': 'Label for the batch number, in the lab report block',
  'coa.tested': 'Label for the date the sample was tested, in the lab report block',
  'coa.view': 'Link that opens the full lab report in a new tab',
  'coa.viewNamed': 'Screen-reader name of a report link in the earlier-reports list; {name} is its date or lab',
  'coa.report': 'Name of an earlier report that has no date or lab to call it by',
  'coa.previous': 'Button that opens the list of earlier lab reports; {count} is how many',
  'coa.newTab': 'Screen-reader hint after a report link: it opens in a new tab',
  'ask.heading': 'Heading of the "message us about this product" block',
  'ask.text': 'Invitation to message the shop about a product',
  'ask.prefill': 'Text pre-filled in the chat when a shopper taps WhatsApp or Telegram on a product',
  'sheet.ships': 'Pre-order flag in the product sheet when a ship date is set',
  'sheet.loadFailed': 'Message in the product sheet when loading fails',
  'sheet.unit': 'Label beside the price in the product sheet',
  'sheet.description': "Heading of a product's description in the sheet",
  'upsells.heading': 'Heading above suggested products on a product page',
} as const satisfies Record<string, string>;
