/** Editor-only notes for area `templates`: where each line appears, in shopper words (Text panel). */
export default {
  'default.hero.aboutAria': 'Screen-reader name of the intro strip above the product grid',
  'default.hero.products': 'Product count in the intro strip above the product grid; {count} is the number of products',
  'default.hero.categories': 'Category count that follows the product count in the intro strip (shown only when there are categories); keep the leading separator; {count} is the number of categories',
  'default.footer.support': 'Heading of the support links column in the footer',
  'default.footer.talk': 'Heading of the chat links column in the footer',
  'bento.hero.aboutAria': 'Screen-reader name of the shop board above the product grid',
  'bento.hero.product': 'Label under the product count on the shop board',
  'bento.hero.category': 'Label under the category count on the shop board',
  'bento.hero.open': 'Status word on the shop board while the shop is taking orders',
  'bento.hero.paused': 'Status word on the shop board while ordering is paused',
  'bento.hero.takingOrders': 'Caption under the status word while the shop is taking orders',
  'bento.hero.orderingPaused': 'Caption under the status word while ordering is paused',
  'bento.hero.orderByToday': 'Dispatch cell headline when the next cut-off is today; {cutoff} is the cut-off time',
  'bento.hero.orderByDay': 'Dispatch cell headline when the next cut-off is on another day; {cutoff} is the time and {day} the weekday name',
  'bento.hero.dispatch': 'Caption under the dispatch cell headline; {date} is the dispatch day',
  'bento.hero.questions': 'Headline of the chat cell on the shop board, above the chat links',
  'bento.day.mon': 'Weekday name in the dispatch cell',
  'bento.day.tue': 'Weekday name in the dispatch cell',
  'bento.day.wed': 'Weekday name in the dispatch cell',
  'bento.day.thu': 'Weekday name in the dispatch cell',
  'bento.day.fri': 'Weekday name in the dispatch cell',
  'bento.day.sat': 'Weekday name in the dispatch cell',
  'bento.day.sun': 'Weekday name in the dispatch cell',
  'bento.footer.support': 'Heading of the support links cell in the footer',
  'bento.footer.talk': 'Heading of the chat links cell in the footer',
  'cyber-brutalism.hero.aboutAria': 'Screen-reader name of the hero above the product grid',
  'cyber-brutalism.hero.statusAria': 'Screen-reader name of the terminal readout of store facts',
  'cyber-brutalism.hero.scene': 'Small terminal-style tag above the shop name in the hero (decorative)',
  'cyber-brutalism.readout.cutoff': 'Readout line with the next dispatch cut-off time; {cutoff} is the time',
  'cyber-brutalism.readout.items': 'Readout line with the number of products; {count} is the number',
  'cyber-brutalism.readout.online': 'Readout line while the shop is taking orders',
  'cyber-brutalism.readout.paused': 'Readout line while ordering is paused',
  'cyber-brutalism.bar.time': 'Label before the clock in the top system strip (decorative)',
  'cyber-brutalism.bar.node': 'Node label in the top system strip; {node} is the node name set in the template options',
  'cyber-brutalism.bar.sku': 'Product count in the top system strip; {count} is the number of products',
  'cyber-brutalism.footer.support': 'Heading of the support links column in the footer, after its number',
  'cyber-brutalism.footer.contact': 'Heading of the chat links column in the footer, after its number',
  'cyber-brutalism.footer.secure': 'Left text of the bottom status strip (decorative)',
  'cyber-brutalism.footer.granted': 'Right text of the bottom status strip (decorative)',
  'dark-luxury.hero.aboutAria': 'Screen-reader name of the hero above the product grid',
  'dark-luxury.hero.products': 'Product count in the hero badge; {count} is the number of products',
  'dark-luxury.hero.categories': 'Category count in the hero badge; {count} is the number of categories',
  'dark-luxury.hero.counts': 'Hero badge joining the product and category counts (shown only when there are categories)',
  'dark-luxury.label.catalogue': 'Small bracketed label above the catalogue heading',
  'dark-luxury.footer.supportAria': 'Screen-reader name of the support links in the footer',
  'dark-luxury.footer.support': 'Heading of the support links column in the footer',
  'dark-luxury.footer.talk': 'Heading of the chat links column in the footer',
  'dark-luxury.status.accepting': 'Footer status badge while the shop is taking orders',
  'dark-luxury.status.paused': 'Footer status badge while ordering is paused',
} as const satisfies Record<string, string>;
