/** Editor-only notes for area `tracking`: where each line appears, in shopper words (Text panel). */
export default {
  'lookup.eyebrow': 'Small label above the title on the order-tracking page',
  'lookup.title': 'Title of the order-tracking page',
  'lookup.lead': 'Line under the title on the order-tracking page',
  'lookup.strip': 'Small heading on the strip above a tracking result',
  'lookup.another': 'Link above a tracking result that goes back to the lookup form',
  'lookup.label': 'Label of the order-number box on the tracking lookup form',
  'lookup.placeholder': 'Example order number shown inside the empty lookup box',
  'lookup.hint': 'Help line under the order-number box',
  'lookup.submit': 'Button that looks up the order',
  'lookup.recent': 'Heading above the orders this browser looked at before',
  'lookup.invalidReference': 'Error beside the order-number label when the number is not in the right shape',
  'hero.summaryAria': 'Screen-reader name of the summary block at the top of a tracking result',
  'hero.orderRef': 'Small line above the headline; {reference} is the order number',
  'hero.headingTo': 'Where the parcel is going, under the headline and on each parcel card; {place} is the destination',
  'hero.parcelsDispatched': 'Line under the headline when an order has several parcels',
  'hero.factPlaced': 'Label of the date the order was placed, in the facts grid',
  'hero.factItems': 'Label of the item count in the facts grid',
  'hero.factLastScan': 'Label of the time of the latest courier scan, in the facts grid',
  'hero.factParcels': 'Label of the parcel count in the facts grid',
  'hero.factType': 'Label of the order type in the facts grid',
  'parcel.single': 'Heading of the parcel card on an order with one parcel',
  'parcel.carrierRef': 'Label of the courier’s own reference number on a parcel card',
  'parcel.trackWith': 'Link to the local carrier’s tracking page; {carrier} is its name',
  'parcel.awaitingScan': 'Small heading of the note on a parcel the courier has not scanned yet, and the stage name before any scan',
  'parcel.notFoundBody': 'Note on a parcel the courier has not scanned yet',
  'parcel.errorEyebrow': 'Small heading of the note when the courier could not be reached for this parcel',
  'parcel.errorBody': 'Note when the courier could not be reached for this parcel',
  'parcel.lastKnown': 'Small heading of the note on a parcel with a tracking number but no live tracking',
  'parcel.awaitingNumber': 'Small heading of the note on a parcel with no tracking number yet',
  'parcel.unavailableBody': 'Note on a parcel that has a tracking number but no live tracking',
  'parcel.noNumberBody': 'Note on a parcel that has no tracking number yet',
  'timeline.title': 'Heading of the list of courier scans on a parcel',
  'timeline.count': 'Number of courier scans beside the Scan history heading',
  'timeline.noTimestamp': 'Shown instead of a date on a courier scan that has none',
  'status.preTransit': 'Parcel status: the shipping label exists but the parcel has not moved',
  'status.customs': 'Parcel status: held for customs',
  'status.outForDelivery': 'Parcel status: with the courier for delivery today',
  'status.availableForPickup': 'Parcel status: waiting for the customer to collect it',
  'status.delivered': 'Parcel status: delivered',
  'status.exception': 'Parcel status: the courier reported a problem',
  'status.returned': 'Parcel status: on its way back to the shop',
  'status.unknown': 'Parcel status shown when the courier status is not known',
  'status.stageOrdered': 'Progress rail stage 1 of 7',
  'status.stageCollected': 'Progress rail stage 2 of 7',
  'status.stageInFlight': 'Progress rail stage 3 of 7',
  'status.stageCustoms': 'Progress rail stage 4 of 7',
  'status.stageLocalCarrier': 'Progress rail stage 5 of 7',
  'status.stageOutForDelivery': 'Progress rail stage 6 of 7',
  'status.stageDelivered': 'Progress rail stage 7 of 7',
  'status.stageSummary': 'Screen-reader sentence for the progress rail; {name} is the current stage name',
  'status.awaitingCourierScan': 'Screen-reader sentence for the progress rail before any courier scan',
  'time.justNow': 'Relative time under a minute',
  'time.minutesAgo': 'Relative time in minutes',
  'time.hoursAgo': 'Relative time in hours',
  'time.daysAgo': 'Relative time in days',
  'time.unknown': 'Shown when a scan or date cannot be read',
  'refresh.checked': 'Freshness line above the Refresh button; {when} is like "12 min ago"',
  'refresh.notChecked': 'Freshness line above the Refresh button before the courier was asked',
  'refresh.availableIn': 'Screen-reader name of the Refresh button while it counts down; {countdown} is minutes and seconds',
  'refresh.label': 'Button that asks the courier for a fresh scan',
  'states.loading': 'Screen-reader name of the placeholder shown while tracking loads',
  'states.verifying': 'Line shown while the security check runs before a lookup',
  'states.blockedHead': 'Heading when the security check never completed',
  'states.blockedBody': 'Text when the security check never completed',
  'states.reload': 'Button on the security-check-failed screen',
  'states.notFoundHead': 'Heading when no order matches the number',
  'states.notFoundBody': 'Text when no order matches the number',
  'states.offHead': 'Heading when the shop has order tracking switched off',
  'states.offBody': 'Text when the shop has order tracking switched off',
  'states.rateHead': 'Heading when this connection has made too many lookups',
  'states.rateBody': 'Text when this connection has made too many lookups',
  'states.challengeHead': 'Heading when the security check was rejected',
  'states.challengeBody': 'Text when the security check was rejected',
  'states.connectionHead': 'Heading when the tracking service could not be reached',
  'states.connectionBody': 'Text when the tracking service could not be reached',
  'states.thisOrder': 'Small heading on a cancelled or refunded order with no parcels',
  'states.noParcels': 'Small heading on an order with no parcels dispatched',
  'states.cancelledBody': 'Text on a cancelled or refunded order; {status} is the order status such as cancelled or refunded',
  'states.preorderBody': 'Text on a pre-order with nothing dispatched',
  'states.notDispatchedBody': 'Text on an order with nothing dispatched yet',
  'states.degradedHead': 'Heading of the notice when the courier network cannot be reached',
  'states.degradedBody': 'Text of the notice when the courier network cannot be reached',
  'states.disabledEyebrow': 'Small label above the title when order lookups are switched off',
  'states.disabledTitle': 'Title when order lookups are switched off on this shop',
  'states.disabledBody': 'Text when order lookups are switched off on this shop',
} as const satisfies Record<string, string>;
