/** Editor-only notes for area `wholesale`: where each line appears, in shopper words (Text panel). */
export default {
  'page.title': 'Heading of the wholesale trade list',
  'page.eyebrow': "Small label above the trade list's load-error and empty-list messages",
  'page.categoryEyebrow': "Small label above the unknown-category message on the trade list",
  'page.searchEyebrow': 'Small label above the "Nothing matches" message on the trade list',
  'page.loadFailedHint': "Text under the \"couldn't load\" heading on the trade list",
  'page.categoryMissingHint': 'Text under the unknown-category heading on the trade list',
  'page.showWholeList': 'Button on the unknown-category message on the trade list',
  'page.wholeList': 'Link beside the heading that leaves an open category on the trade list',
  'page.noMatchesHint': 'Text under "Nothing matches" on the trade list',
  'page.emptyHint': 'Text under "Nothing stocked here yet" on the trade list',
  'search.withCode': 'Placeholder of the trade-list search box when product codes are shown',
  'search.plain': 'Placeholder of the trade-list search box when product codes are hidden',
  'tally.unit': 'Word after the number of products in the trade-list heading tally',
  'tally.of': 'Between the shown and total counts in the trade-list tally while a search is active',
  'table.code': 'Column heading: product code',
  'table.product': 'Column heading: product name',
  'table.unit': 'Column heading: unit price',
  'table.bulk': 'Column heading: bulk price breaks',
  'table.line': 'Column heading: line total',
  'table.qty': 'Column heading: quantity',
  'bar.lines': 'Number of product lines in the trade-list basket bar',
  'bar.units': 'Number of units in the trade-list basket bar',
  'bar.tally': 'Visible tally in the basket bar; {lines} and {units} are the two counts above',
  'bar.ariaLabel': 'Screen-reader label of the basket bar link',
  'bar.viewBasket': 'Button text in the trade-list basket bar',
  'ladder.minUnits': 'Price-break row: the quantity from which the price applies',
  'ladder.yourPrice': 'Tag on the price-break row that applies to the quantity in the basket',
  'row.min': 'Chip on a trade-list row with a minimum order quantity',
  'row.bulkPriceApplied': 'Screen-reader label of the bulk chip when a break applies; {percent} is the saving, {name} the product',
  'row.showBreaks': 'Screen-reader label of the bulk chip when no break applies yet',
  'row.bulk': 'Bulk chip on a trade-list row that has price breaks',
  'row.removeAria': 'Screen-reader label of Remove on an unavailable trade-list row',
} as const satisfies Record<string, string>;
