import { defineTextArea } from '@/text/define.ts';

/** Area `account`: the signed-in shopper's account pages (orders, loyalty, referrals, profile). */
export default defineTextArea('account', {
  'nav.orders': { en: 'Orders', max: 30 },
  'nav.loyalty': { en: 'Loyalty', max: 30 },
  'nav.referrals': { en: 'Referrals', max: 30 },
  'nav.profile': { en: 'Profile', max: 30 },
  'nav.ariaLabel': { en: 'Account sections', max: 60 },
  'layout.eyebrow': { en: 'Account', max: 30 },
  'layout.standing': { en: 'Member since {date} · {orders}', max: 80 },
  'orders.count': { en: { one: '{count} order', other: '{count} orders' }, max: 40 },
  'orders.loadFailedTitle': { en: "We couldn't load your orders", max: 80 },
  'orders.loadFailedBody': { en: 'Your history is safe — this was a hiccup between your browser and us.' },
  'orders.emptyTitle': { en: 'No orders yet', max: 80 },
  'orders.emptyBody': { en: 'Everything you order shows up here, with what you paid and where it is.' },
  'orders.title': { en: 'Order history', max: 60 },
  'orders.balanceDue': { en: 'Balance due {amount}', max: 60 },
  'orders.loadingMore': { en: 'Loading', max: 40 },
  'orders.loadMore': { en: 'Load more', max: 40 },
  'order.title': { en: 'Order', max: 30 },
  'order.notFoundTitle': { en: "We can't find that order", max: 80 },
  'order.loadFailedTitle': { en: "We couldn't load that order", max: 80 },
  'order.notFoundBody': { en: 'It may belong to another account, or the reference may be wrong.' },
  'order.loadFailedBody': { en: 'The order is safe — this was a hiccup between your browser and us.' },
  'order.allOrders': { en: 'All orders', max: 40 },
  'order.backToOrders': { en: '← All orders', max: 40 },
  'order.placed': { en: 'Placed {date}', max: 60 },
  'order.collectFrom': { en: 'Collect from {name}', max: 80 },
  'order.balanceDue': { en: 'Balance due', max: 40 },
  'order.payHelp': { en: "This balance can't be paid online. Contact us and we'll help.", max: 160 },
  'order.items': { en: 'Items', max: 40 },
  'order.lines': { en: { one: '{count} line', other: '{count} lines' }, max: 40 },
  'order.payments': { en: 'Payments', max: 40 },
  'order.parcels': { en: 'Parcels', max: 40 },
  'order.parcelCount': { en: { one: '{count} parcel', other: '{count} parcels' }, max: 40 },
  'order.parcelFallback': { en: 'Parcel', max: 40 },
  'order.awaitingDispatch': { en: 'Awaiting dispatch', max: 60 },
  'order.shippedFallback': { en: 'Shipped', max: 40 },
  'order.trackParcel': { en: 'Track this parcel', max: 60 },
  'loyalty.redeemedToast': { en: '{credit} credit added — you now have {points} points and {balance} in credit.', max: 300 },
  'loyalty.redeemFailed': { en: "We couldn't redeem that", max: 80 },
  'loyalty.loadFailedTitle': { en: "We couldn't load your points", max: 80 },
  'loyalty.loadFailedBody': { en: 'Your balance is safe — this was a hiccup between your browser and us.' },
  'loyalty.points': { en: 'Points', max: 30 },
  'loyalty.storeCredit': { en: 'Store credit', max: 40 },
  'loyalty.noPoints': { en: 'Points land on your orders — they’ll show up here.' },
  'loyalty.redeemAria': { en: 'Redeem points', max: 60 },
  'loyalty.redeemTitle': { en: 'Redeem', max: 40 },
  'loyalty.redeem': { en: 'Redeem', max: 40 },
  'loyalty.nothingToRedeem': { en: 'There’s nothing to redeem for right now.' },
  'loyalty.cost': { en: '{points} pts', max: 30 },
  'loyalty.worth': { en: 'Worth {credit}', max: 60 },
  'loyalty.pointsToGo': { en: '{points} points to go', max: 60 },
  'loyalty.confirmTitle': { en: 'Confirm redemption', max: 60 },
  'loyalty.confirmBody': { en: '{reward} costs {points} points, and adds {credit} of credit to your account. Credit is spent at checkout.', max: 300 },
  'loyalty.redeeming': { en: 'Redeeming', max: 30 },
  'profile.loadFailedTitle': { en: "We couldn't load your profile", max: 80 },
  'profile.loadFailedBody': { en: 'This was a hiccup between your browser and us.' },
  'profile.detailsTitle': { en: 'Your details', max: 40 },
  'profile.name': { en: 'Name', max: 30 },
  'profile.nameNotSet': { en: 'Not set', max: 30 },
  'profile.memberSince': { en: 'Member since', max: 40 },
  'profile.orders': { en: 'Orders', max: 30 },
  'profile.totalSpend': { en: 'Total spend', max: 40 },
  'profile.channelsAria': { en: 'Sign-in channels', max: 60 },
  'profile.channelsTitle': { en: 'Ways in', max: 40 },
  'profile.email': { en: 'Email', max: 30 },
  'profile.channelLinked': { en: '{channel} linked', max: 60 },
  'profile.channelNotLinked': { en: '{channel} not linked', max: 60 },
  'profile.channelsNote': { en: 'Any linked channel signs you into this account — talk to us in a chat to add another.' },
  'profile.contactAria': { en: 'Contact', max: 40 },
  'profile.talkToUs': { en: 'Talk to us', max: 40 },
  'profile.signingOut': { en: 'Signing out', max: 40 },
  'profile.signOut': { en: 'Sign out', max: 40 },
  'profile.botAria': { en: 'Classic bot', max: 40 },
  'profile.botTitle': { en: 'Prefer the classic bot?', max: 60 },
  'profile.botNote': { en: 'Shop with buttons in the chat instead of this app. You can come back from the bot’s menu any time.' },
  'profile.botSwitch': { en: 'Switch to the classic bot', max: 60 },
  'profile.botSwitching': { en: 'Switching…', max: 40 },
  'profile.botConfirm': { en: 'Yes, switch', max: 40 },
  'profile.botFailed': { en: "We couldn't switch you — try again", max: 100 },
  'referrals.referredToast': { en: "You're now referred by {name}.", max: 100 },
  'referrals.loadFailedTitle': { en: "We couldn't load your referrals", max: 80 },
  'referrals.loadFailedBody': { en: "Your code hasn't gone anywhere — this was a hiccup between your browser and us." },
  'referrals.yourCode': { en: 'Your referral code', max: 40 },
  'referrals.copyAria': { en: 'Copy your referral code {code}', max: 100 },
  'referrals.share': { en: 'Share', max: 30 },
  'referrals.shareNote': { en: 'The invite goes out with your code already in it — send it to whoever you want to bring in.' },
  'referrals.shareText': { en: 'Shopping with {shop}? Use my referral code {code} on your first order.', max: 200 },
  'referrals.broughtInAria': { en: 'Your referrals', max: 40 },
  'referrals.broughtInTitle': { en: 'What it has brought in', max: 60 },
  'referrals.peopleReferred': { en: 'People referred', max: 40 },
  'referrals.ordersEarned': { en: 'Orders earned on', max: 40 },
  'referrals.referrerAria': { en: 'Who referred you', max: 40 },
  'referrals.referrerTitle': { en: 'Were you referred?', max: 60 },
  'referrals.referredBy': { en: 'Referred by', max: 40 },
  'referrals.someone': { en: 'Someone at the shop', max: 40 },
  'referrals.enterCodeNote': { en: 'Enter their code once and it stays on your account. You can’t change it later.' },
  'referrals.codeAria': { en: 'Referral code', max: 40 },
  'referrals.codePlaceholder': { en: 'Their code', max: 40 },
  'referrals.checking': { en: 'Checking', max: 30 },
  'referrals.apply': { en: 'Apply', max: 30 },
  'referrals.codeFailed': { en: "That code didn't work", max: 80 },
  'password.aria': { en: 'Password', max: 40 },
  'password.title': { en: 'Password', max: 40 },
  'password.setNote': { en: 'A password is set on this account.', max: 120 },
  'password.unsetNote': { en: 'No password yet. Set one to sign in with your email or phone.', max: 160 },
  'password.signInWith': { en: 'You sign in with', max: 60 },
  'password.emailRow': { en: 'Email', max: 30 },
  'password.phoneRow': { en: 'Phone', max: 30 },
  'password.verified': { en: 'Verified', max: 30 },
  'password.unverified': { en: 'Not verified', max: 30 },
  'password.sendVerification': { en: 'Send verification email', max: 50 },
  'password.sendingVerification': { en: 'Sending…', max: 30 },
  'password.verificationSent': { en: 'Verification email sent — check your inbox.', max: 100 },
  'password.setCta': { en: 'Set a password', max: 40 },
  'password.changeCta': { en: 'Change password', max: 40 },
  'password.current': { en: 'Current password', max: 40 },
  'password.new': { en: 'New password', max: 40 },
  'password.identifierHint': { en: 'Add the email or phone you’ll sign in with.', max: 120 },
  'password.save': { en: 'Save password', max: 40 },
  'password.saving': { en: 'Saving…', max: 30 },
  'password.saved': { en: 'Password saved.', max: 60 },
});
