import { defineTextArea } from '@/text/define.ts';

/** Area `account`: the signed-in shopper's account pages (orders, loyalty, referrals, profile). */
export default defineTextArea('account', {
  'nav.orders': { en: 'Orders', note: 'Account section tab, and the small label on the orders error and empty screens', max: 30 },
  'nav.loyalty': { en: 'Loyalty', note: 'Account section tab, and the small label on the loyalty error screen', max: 30 },
  'nav.referrals': { en: 'Referrals', note: 'Account section tab, and the small label on the referrals error screen', max: 30 },
  'nav.profile': { en: 'Profile', note: 'Account section tab, and the small label on the profile error screen', max: 30 },
  'nav.ariaLabel': { en: 'Account sections', note: 'Screen-reader name of the account section tabs', max: 60 },
  'layout.eyebrow': { en: 'Account', note: "Small label above the shopper's name at the top of every account page", max: 30 },
  'layout.standing': { en: 'Member since {date} · {orders}', note: "Line under the shopper's name; {date} is when they joined and {orders} is their order count", max: 80 },
  'orders.count': { en: { one: '{count} order', other: '{count} orders' }, note: 'Order count on the account header and above the order list', max: 40 },
  'orders.loadFailedTitle': { en: "We couldn't load your orders", note: 'Heading when the order history fails to load', max: 80 },
  'orders.loadFailedBody': { en: 'Your history is safe — this was a hiccup between your browser and us.', note: 'Text under the heading when the order history fails to load' },
  'orders.emptyTitle': { en: 'No orders yet', note: 'Heading of the order history when the shopper has no orders', max: 80 },
  'orders.emptyBody': { en: 'Everything you order shows up here, with what you paid and where it is.', note: 'Text under the heading of an empty order history' },
  'orders.title': { en: 'Order history', note: 'Heading above the list of orders', max: 60 },
  'orders.balanceDue': { en: 'Balance due ', note: 'Label before the amount still owed on an order row (keep the space at the end)', max: 40 },
  'orders.loadingMore': { en: 'Loading', note: 'Label of the Load more button while the next page of orders loads', max: 40 },
  'orders.loadMore': { en: 'Load more', note: 'Button at the end of the order list that shows older orders', max: 40 },
  'order.title': { en: 'Order', note: 'Small label above the heading when a single order fails to load', max: 30 },
  'order.notFoundTitle': { en: "We can't find that order", note: "Heading when the order link does not match any of the shopper's orders", max: 80 },
  'order.loadFailedTitle': { en: "We couldn't load that order", note: 'Heading when one order fails to load', max: 80 },
  'order.notFoundBody': { en: 'It may belong to another account, or the reference may be wrong.', note: 'Text under the heading when an order cannot be found' },
  'order.loadFailedBody': { en: 'The order is safe — this was a hiccup between your browser and us.', note: 'Text under the heading when one order fails to load' },
  'order.allOrders': { en: 'All orders', note: 'Button back to the order list from the order-not-found screen', max: 40 },
  'order.backToOrders': { en: '← All orders', note: 'Link at the top of an order that goes back to the order list', max: 40 },
  'order.placed': { en: 'Placed ', note: 'Label before the order date at the top of an order (keep the space at the end)', max: 30 },
  'order.balanceDue': { en: 'Balance due', note: 'Banner on an order that still has money owed', max: 40 },
  'order.items': { en: 'Items', note: 'Heading of the items section of an order', max: 40 },
  'order.lines': { en: { one: '{count} line', other: '{count} lines' }, note: 'Number of item lines, beside the Items heading', max: 40 },
  'order.payments': { en: 'Payments', note: 'Heading of the payments section of an order', max: 40 },
  'order.parcels': { en: 'Parcels', note: 'Heading of the parcels section of an order', max: 40 },
  'order.parcelCount': { en: { one: '{count} parcel', other: '{count} parcels' }, note: 'Number of parcels, beside the Parcels heading', max: 40 },
  'order.parcelFallback': { en: 'Parcel', note: 'Name of a parcel that has no carrier name', max: 40 },
  'order.awaitingDispatch': { en: 'Awaiting dispatch', note: 'Shown on a parcel with no tracking number and no dispatch date yet', max: 60 },
  'order.shippedFallback': { en: 'Shipped', note: 'Status of a parcel whose status is not one the shop recognises', max: 40 },
  'order.trackParcel': { en: 'Track this parcel', note: "Link to the carrier's tracking page for a parcel", max: 60 },
  'order.openOrderPage': { en: 'Open order page', note: "Button that opens the order's own page", max: 60 },
  'order.orderPageNote': { en: 'The order page is where you pay, change payment method and follow the parcel — share it with us if you need help with this order.', note: 'Text under the Open order page button', max: 300 },
  'loyalty.redeemedToast': { en: '{credit} credit added — you now have {points} points and {balance} in credit.', note: 'Pop-up after redeeming points; {credit} is the credit gained, {points} the new points balance, {balance} the new credit balance', max: 300 },
  'loyalty.redeemFailed': { en: "We couldn't redeem that", note: 'Pop-up when redeeming points fails', max: 80 },
  'loyalty.loadFailedTitle': { en: "We couldn't load your points", note: 'Heading when the loyalty page fails to load', max: 80 },
  'loyalty.loadFailedBody': { en: 'Your balance is safe — this was a hiccup between your browser and us.', note: 'Text under the heading when the loyalty page fails to load' },
  'loyalty.points': { en: 'Points', note: 'Unit label beside the big points balance', max: 30 },
  'loyalty.storeCredit': { en: 'Store credit', note: "Row label for the shopper's store credit balance", max: 40 },
  'loyalty.noPoints': { en: 'Points land on your orders — they’ll show up here.', note: 'Shown under the balance when the shopper has no points yet' },
  'loyalty.redeemAria': { en: 'Redeem points', note: 'Screen-reader name of the redeem section', max: 60 },
  'loyalty.redeem': { en: 'Redeem', note: 'Heading of the redeem section, and the Redeem buttons', max: 40 },
  'loyalty.nothingToRedeem': { en: 'There’s nothing to redeem for right now.', note: 'Shown when the shop has no redemption options' },
  'loyalty.cost': { en: '{points} pts', note: 'Points cost of a redemption option; {points} is a formatted number', max: 30 },
  'loyalty.worth': { en: 'Worth {credit}', note: 'Credit value of a redemption option the shopper can afford; {credit} is money', max: 60 },
  'loyalty.pointsToGo': { en: '{points} points to go', note: 'Shown on a redemption option the shopper cannot afford yet; {points} is the shortfall', max: 60 },
  'loyalty.confirmTitle': { en: 'Confirm redemption', note: 'Title of the confirmation pop-up before redeeming', max: 60 },
  'loyalty.confirmBody': { en: '{reward} costs {points} points, and adds {credit} of credit to your account. Credit is spent at checkout.', note: 'Text of the redemption confirmation; {reward} is the option name, {points} the cost, {credit} the credit gained', max: 300 },
  'loyalty.cancel': { en: 'Cancel', note: 'Button that closes the redemption confirmation', max: 30 },
  'loyalty.redeeming': { en: 'Redeeming', note: 'Confirm button label while the redemption is being processed', max: 30 },
  'profile.loadFailedTitle': { en: "We couldn't load your profile", note: 'Heading when the profile page fails to load', max: 80 },
  'profile.loadFailedBody': { en: 'This was a hiccup between your browser and us.', note: 'Text under the heading when the profile page fails to load' },
  'profile.detailsTitle': { en: 'Your details', note: 'Heading of the profile details', max: 40 },
  'profile.name': { en: 'Name', note: "Profile row label for the shopper's name", max: 30 },
  'profile.nameNotSet': { en: 'Not set', note: 'Profile value when the shopper has no name', max: 30 },
  'profile.memberSince': { en: 'Member since', note: 'Profile row label for the join date', max: 40 },
  'profile.orders': { en: 'Orders', note: 'Profile row label for the number of orders', max: 30 },
  'profile.totalSpend': { en: 'Total spend', note: 'Profile row label for what the shopper has spent', max: 40 },
  'profile.channelsAria': { en: 'Sign-in channels', note: 'Screen-reader name of the sign-in channels section', max: 60 },
  'profile.channelsTitle': { en: 'Ways in', note: 'Heading of the list of sign-in channels', max: 40 },
  'profile.email': { en: 'Email', note: 'Sign-in channel name', max: 30 },
  'profile.channelLinked': { en: '{channel} linked', note: 'Sign-in channel the shopper has linked; {channel} is Telegram, WhatsApp or Email', max: 60 },
  'profile.channelNotLinked': { en: '{channel} not linked', note: 'Sign-in channel the shopper has not linked; {channel} is Telegram, WhatsApp or Email', max: 60 },
  'profile.channelsNote': { en: 'Any linked channel signs you into this account — talk to us in a chat to add another.', note: 'Text under the sign-in channels list' },
  'profile.contactAria': { en: 'Contact', note: 'Screen-reader name of the contact section', max: 40 },
  'profile.talkToUs': { en: 'Talk to us', note: "Heading above the shop's chat links on the profile page", max: 40 },
  'profile.signingOut': { en: 'Signing out', note: 'Sign out button label while signing out', max: 40 },
  'profile.signOut': { en: 'Sign out', note: 'Button that signs the shopper out', max: 40 },
  'profile.botAria': { en: 'Classic bot', note: 'Screen-reader name of the switch-to-classic-bot section', max: 40 },
  'profile.botTitle': { en: 'Prefer the classic bot?', note: 'Heading of the switch-to-classic-bot section (Telegram beta only)', max: 60 },
  'profile.botNote': { en: 'Shop with buttons in the chat instead of this app. You can come back from the bot’s menu any time.', note: 'Text explaining the switch to the classic Telegram bot' },
  'profile.botSwitch': { en: 'Switch to the classic bot', note: 'Button that starts the switch to the classic bot', max: 60 },
  'profile.botSwitching': { en: 'Switching…', note: 'Confirm button label while switching to the classic bot', max: 40 },
  'profile.botConfirm': { en: 'Yes, switch', note: 'Button that confirms the switch to the classic bot', max: 40 },
  'profile.botCancel': { en: 'Cancel', note: 'Button that backs out of switching to the classic bot', max: 30 },
  'profile.botFailed': { en: "We couldn't switch you — try again", note: 'Message when switching to the classic bot fails', max: 100 },
  'referrals.referredToast': { en: "You're now referred by {name}.", note: 'Pop-up after entering a referral code; {name} is the person who referred them', max: 100 },
  'referrals.loadFailedTitle': { en: "We couldn't load your referrals", note: 'Heading when the referrals page fails to load', max: 80 },
  'referrals.loadFailedBody': { en: "Your code hasn't gone anywhere — this was a hiccup between your browser and us.", note: 'Text under the heading when the referrals page fails to load' },
  'referrals.yourCode': { en: 'Your referral code', note: "Label above the shopper's own referral code", max: 40 },
  'referrals.copyAria': { en: 'Copy your referral code {code}', note: 'Screen-reader name of the Copy button; {code} is the referral code', max: 100 },
  'referrals.share': { en: 'Share', note: 'Button that opens the device share sheet with the invite', max: 30 },
  'referrals.shareNote': { en: 'The invite goes out with your code already in it — send it to whoever you want to bring in.', note: 'Text under the share buttons' },
  'referrals.shareText': { en: 'Shopping with {shop}? Use my referral code {code} on your first order.', note: 'The invite message sent to a friend; {shop} is the shop name, {code} the referral code', max: 200 },
  'referrals.broughtInAria': { en: 'Your referrals', note: 'Screen-reader name of the referral results section', max: 40 },
  'referrals.broughtInTitle': { en: 'What it has brought in', note: 'Heading above the referral counts', max: 60 },
  'referrals.peopleReferred': { en: 'People referred', note: 'Label under the number of people the shopper has referred', max: 40 },
  'referrals.ordersEarned': { en: 'Orders earned on', note: 'Label under the number of referred orders that earned rewards', max: 40 },
  'referrals.referrerAria': { en: 'Who referred you', note: 'Screen-reader name of the referred-by section', max: 40 },
  'referrals.referrerTitle': { en: 'Were you referred?', note: 'Heading of the referred-by section', max: 60 },
  'referrals.referredBy': { en: 'Referred by', note: 'Label before the name of the person who referred the shopper', max: 40 },
  'referrals.someone': { en: 'Someone at the shop', note: 'Shown when the referrer has no name', max: 40 },
  'referrals.enterCodeNote': { en: 'Enter their code once and it stays on your account. You can’t change it later.', note: 'Text above the referral code field' },
  'referrals.codeAria': { en: 'Referral code', note: 'Screen-reader name of the referral code field', max: 40 },
  'referrals.codePlaceholder': { en: 'Their code', note: 'Placeholder in the referral code field', max: 40 },
  'referrals.checking': { en: 'Checking', note: 'Apply button label while the referral code is checked', max: 30 },
  'referrals.apply': { en: 'Apply', note: 'Button that submits the referral code', max: 30 },
  'referrals.codeFailed': { en: "That code didn't work", note: 'Message when a referral code is rejected', max: 80 },
});
