import { defineTextArea } from '@/text/define.ts';

/** Area `auth`: the sign-in page and modal, WhatsApp and Telegram sign-in, and the Telegram web-app sign-in error. */
export default defineTextArea('auth', {
  'modal.lede': { en: 'There’s no password — sign in from a chat app you already use.', note: 'Line under the heading of the sign-in pop-up', max: 200 },
  'page.title': { en: 'Sign in to {name}', note: 'Heading of the sign-in page; {name} is the shop name', max: 80 },
  'page.lede': { en: 'There’s no password. Sign in from a chat app you already use, and your orders, points and referrals are waiting.', note: 'Line under the heading of the sign-in page', max: 300 },
  'options.unavailableTitle': { en: 'Sign-in isn’t available right now', note: 'Heading shown when the shop has no sign-in method switched on', max: 80 },
  'options.unavailableBody': { en: "Message {name} and we'll sort it out with you directly.", note: 'Shown under the heading when no sign-in method is on; {name} is the shop name', max: 200 },
  'options.signingIn': { en: 'Signing you in', note: 'Note under the Telegram button while the sign-in is being checked', max: 60 },
  'options.soon': { en: 'Coming soon.', note: 'Inside the greyed-out email or phone sign-in card', max: 60 },
  'options.emailOrPhone': { en: 'Email or phone', note: 'Title of the greyed-out email or phone sign-in card', max: 60 },
  'telegram.previewNote': { en: 'Preview: Telegram’s sign-in button shows here on your live shop', note: 'Shown in the page builder where the Telegram sign-in button will be', max: 200 },
  'telegram.widgetMissing': { en: 'Telegram sign-in isn’t loading on this address', note: 'Warning under the Telegram card when the Telegram sign-in button does not appear', max: 200 },
  'telegram.widgetFailed': { en: "We couldn't sign you in with Telegram", note: 'Error under the Telegram button when the sign-in fails', max: 120 },
  'telegram.errorTitle': { en: 'Couldn’t sign you in through Telegram', note: 'Heading when signing in inside the Telegram app fails', max: 120 },
  'telegram.errorBody': { en: 'Close and reopen the shop from the bot.{detail}', note: 'Under the Telegram sign-in error heading; {detail} is an optional reason in brackets, keep it at the end', max: 200 },
  'telegram.noAccount': { en: "Telegram didn't pass your account to the shop", note: 'Reason shown when Telegram sends no account details to the shop', max: 120 },
  'telegram.signInFailed': { en: "Couldn't sign you in through Telegram", note: 'Reason shown when the Telegram app sign-in request fails', max: 120 },
  'login.basketFailed': { en: "We couldn't add your basket to your account", note: 'Pop-up message when the basket cannot be merged into the account after signing in', max: 120 },
  'whatsapp.received': { en: 'Message received — signing you in', note: "WhatsApp sign-in, once the shopper's message has arrived", max: 80 },
  'whatsapp.expiredNote': { en: 'That code expired', note: 'WhatsApp sign-in, when the code has run out', max: 60 },
  'whatsapp.expiredBody': { en: 'A code is only good for a few minutes. Start a new one when you’re ready to send it.', note: 'WhatsApp sign-in, under "That code expired"', max: 200 },
  'whatsapp.startAgain': { en: 'Start again', note: 'Button to get a new WhatsApp code', max: 40 },
  'whatsapp.failed': { en: 'Something went wrong', note: 'WhatsApp sign-in error when no reason is available', max: 80 },
  'whatsapp.open': { en: 'Open WhatsApp', note: 'Button that opens WhatsApp with the sign-in message ready', max: 40 },
  'whatsapp.sendCodeTo': { en: 'Or send this code to {number}', note: "Label above the sign-in code; {number} is the shop's WhatsApp number", max: 80 },
  'whatsapp.sendCodeToUs': { en: 'Or send this code to us on WhatsApp', note: 'Label above the sign-in code when the shop has no WhatsApp number to show', max: 80 },
  'whatsapp.copyCode': { en: 'Copy the code {code}', note: 'Screen-reader label of the Copy button; {code} is the sign-in code', max: 80 },
  'whatsapp.waiting': { en: 'Waiting for your message', note: 'WhatsApp sign-in, while waiting for the shopper to send the code; a countdown follows', max: 60 },
  'whatsapp.intro': { en: 'Send us one message from WhatsApp and you’re in. Nothing to remember, nothing to type back.', note: 'WhatsApp card, before the shopper starts', max: 200 },
  'whatsapp.starting': { en: 'Starting…', note: 'WhatsApp button label while the code is being created', max: 40 },
  'whatsapp.continue': { en: 'Continue with WhatsApp', note: 'WhatsApp card main button', max: 60 },
  'whatsapp.finishFailed': { en: "We couldn't finish signing you in", note: 'WhatsApp sign-in error when the last step fails', max: 120 },
  'whatsapp.startFailed': { en: "We couldn't start a WhatsApp sign-in", note: 'WhatsApp sign-in error when the code cannot be created', max: 120 },
});
