import { defineTextArea } from '@/text/define.ts';

/** Area `auth`: the sign-in page and modal, WhatsApp and Telegram sign-in, and the Telegram web-app sign-in error. */
export default defineTextArea('auth', {
  'modal.lede': { en: 'There’s no password — sign in from a chat app you already use.', max: 200 },
  'page.title': { en: 'Sign in to {name}', max: 80 },
  'page.lede': { en: 'There’s no password. Sign in from a chat app you already use, and your orders, points and referrals are waiting.', max: 300 },
  'options.unavailableTitle': { en: 'Sign-in isn’t available right now', max: 80 },
  'options.unavailableBody': { en: "Message {name} and we'll sort it out with you directly.", max: 200 },
  'options.signingIn': { en: 'Signing you in', max: 60 },
  'options.soon': { en: 'Coming soon.', max: 60 },
  'options.emailOrPhone': { en: 'Email or phone', max: 60 },
  'telegram.previewNote': { en: 'Preview: Telegram’s sign-in button shows here on your live shop', max: 200 },
  'telegram.widgetMissing': { en: 'Telegram sign-in isn’t loading on this address', max: 200 },
  'telegram.widgetFailed': { en: "We couldn't sign you in with Telegram", max: 120 },
  'telegram.errorTitle': { en: 'Couldn’t sign you in through Telegram', max: 120 },
  'telegram.errorBody': { en: 'Close and reopen the shop from the bot.{detail}', max: 200 },
  'telegram.noAccount': { en: "Telegram didn't pass your account to the shop", max: 120 },
  'telegram.signInFailed': { en: "Couldn't sign you in through Telegram", max: 120 },
  'login.basketFailed': { en: "We couldn't add your basket to your account", max: 120 },
  'whatsapp.received': { en: 'Message received — signing you in', max: 80 },
  'whatsapp.expiredNote': { en: 'That code expired', max: 60 },
  'whatsapp.expiredBody': { en: 'A code is only good for a few minutes. Start a new one when you’re ready to send it.', max: 200 },
  'whatsapp.startAgain': { en: 'Start again', max: 40 },
  'whatsapp.open': { en: 'Open WhatsApp', max: 40 },
  'whatsapp.sendCodeTo': { en: 'Or send this code to {number}', max: 80 },
  'whatsapp.sendCodeToUs': { en: 'Or send this code to us on WhatsApp', max: 80 },
  'whatsapp.copyCode': { en: 'Copy the code {code}', max: 80 },
  'whatsapp.waiting': { en: 'Waiting for your message', max: 60 },
  'whatsapp.intro': { en: 'Send us one message from WhatsApp and you’re in. Nothing to remember, nothing to type back.', max: 200 },
  'whatsapp.starting': { en: 'Starting…', max: 40 },
  'whatsapp.continue': { en: 'Continue with WhatsApp', max: 60 },
  'whatsapp.finishFailed': { en: "We couldn't finish signing you in", max: 120 },
  'whatsapp.startFailed': { en: "We couldn't start a WhatsApp sign-in", max: 120 },
  'password.invalid': { en: 'Email/phone or password is incorrect', max: 100 },
  'password.wrongCurrent': { en: 'Your current password is incorrect', max: 100 },
  'password.taken': { en: 'That email or phone can’t be used to create an account. Try signing in or resetting your password.', max: 200 },
  'password.banned': { en: 'This account can’t sign in right now. Contact the shop for help.', max: 160 },
  'password.unavailable': { en: 'Password sign-in isn’t available right now.', max: 120 },
  'password.tooShort': { en: 'Use at least 8 characters', max: 80 },
  'password.tooLong': { en: 'That password is too long — shorten it a little', max: 100 },
  'password.phoneInvalid': { en: 'Enter your phone number with its country code', max: 100 },
});
