import { defineTextArea } from '@/text/define.ts';

/** Area `auth`: the sign-in page and modal, WhatsApp and Telegram sign-in, and the Telegram web-app sign-in error. */
export default defineTextArea('auth', {
  'modal.lede': { en: 'Sign in to pick up where you left off.', max: 200 },
  'page.title': { en: 'Sign in to {name}', max: 80 },
  'page.lede': { en: 'Choose how you’d like to sign in.', max: 300 },
  'options.unavailableTitle': { en: 'Sign-in isn’t available right now', max: 80 },
  'options.unavailableBody': { en: "Message {name} and we'll sort it out with you directly.", max: 200 },
  'options.signingIn': { en: 'Signing you in', max: 60 },
  'options.or': { en: 'or', max: 20 },
  'telegram.continue': { en: 'Continue with Telegram', max: 60 },
  'telegram.previewNote': { en: 'Preview: Telegram’s sign-in button shows here on your live shop', max: 200 },
  'telegram.widgetMissing': { en: 'Telegram sign-in isn’t loading on this address', max: 200 },
  'telegram.widgetFailed': { en: "We couldn't sign you in with Telegram", max: 120 },
  'telegram.errorTitle': { en: 'Couldn’t sign you in through Telegram', max: 120 },
  'telegram.errorBody': { en: 'Close and reopen the shop from the bot.{detail}', max: 200 },
  'telegram.starting': { en: 'Opening Telegram…', max: 60 },
  'telegram.startFailed': { en: "We couldn't open Telegram. Please try again.", max: 120 },
  'telegram.unavailable': { en: 'Telegram sign-in isn’t available right now.', max: 120 },
  'telegram.callback.title': { en: 'Signing you in', max: 60 },
  'telegram.callback.checking': { en: 'Checking with Telegram…', max: 80 },
  'telegram.callback.errorTitle': { en: 'Couldn’t sign you in', max: 60 },
  'telegram.callback.expired': { en: 'This sign-in was started in another browser or tab, or it ran out of time. Please try again.', max: 200 },
  'telegram.callback.failed': { en: "Telegram couldn't confirm your sign-in. Please try again.", max: 160 },
  'telegram.callback.cancelled': { en: 'You cancelled the sign-in with Telegram.', max: 120 },
  'telegram.callback.generic': { en: "We couldn't finish signing you in. Please try again.", max: 120 },
  'telegram.noAccount': { en: "Telegram didn't pass your account to the shop", max: 120 },
  'telegram.signInFailed': { en: "Couldn't sign you in through Telegram", max: 120 },
  'login.basketFailed': { en: "We couldn't add your basket to your account", max: 120 },
  'whatsapp.received': { en: 'Message received — signing you in', max: 80 },
  'whatsapp.expiredNote': { en: 'That code expired', max: 60 },
  'whatsapp.expiredBody': { en: 'A code is only good for a few minutes. Start a new one when you’re ready to send it.', max: 200 },
  'whatsapp.startAgain': { en: 'Start again', max: 40 },
  'whatsapp.open': { en: 'Open WhatsApp', max: 40 },
  'whatsapp.sendCodeTo': { en: 'Or send this code to {number}', max: 80 },
  'whatsapp.sendCodeToUs': { en: 'Or send this code to us on WhatsApp', max: 80 },
  'whatsapp.copyCode': { en: 'Copy the code {code}', max: 80 },
  'whatsapp.waiting': { en: 'Waiting for your message', max: 60 },
  'whatsapp.back': { en: 'Choose another way', max: 50 },
  'whatsapp.starting': { en: 'Starting…', max: 40 },
  'whatsapp.continue': { en: 'Continue with WhatsApp', max: 60 },
  'whatsapp.finishFailed': { en: "We couldn't finish signing you in", max: 120 },
  'whatsapp.startFailed': { en: "We couldn't start a WhatsApp sign-in", max: 120 },
  'password.invalid': { en: 'Email/phone or password is incorrect', max: 100 },
  'password.wrongCurrent': { en: 'Your current password is incorrect', max: 100 },
  'password.taken': { en: 'That email or phone can’t be used to create an account. Try signing in or resetting your password.', max: 200 },
  'password.banned': { en: 'This account can’t sign in right now. Contact the shop for help.', max: 160 },
  'password.unavailable': { en: 'Password sign-in isn’t available right now.', max: 120 },
  'password.tooShort': { en: 'Use at least 8 characters', max: 80 },
  'password.tooLong': { en: 'That password is too long — shorten it a little', max: 100 },
  'password.phoneInvalid': { en: 'Enter your phone number with its country code', max: 100 },
  'password.show': { en: 'Show password', max: 40 },
  'password.hide': { en: 'Hide password', max: 40 },
  'password.kindAria': { en: 'Use your email or your phone', max: 60 },
  'password.byEmail': { en: 'Email', max: 20 },
  'password.byPhone': { en: 'Phone', max: 20 },
  'password.emailLabel': { en: 'Email address', max: 40 },
  'password.passwordLabel': { en: 'Password', max: 40 },
  'password.createLabel': { en: 'Create a password', max: 40 },
  'password.rule': { en: 'Use at least 8 characters.', max: 80 },
  'password.submitSignIn': { en: 'Sign in', max: 40 },
  'password.signUpTitle': { en: 'Create your account', max: 60 },
  'password.submitSignUp': { en: 'Create account', max: 40 },
  'password.working': { en: 'One moment…', max: 40 },
  'password.toSignUp': { en: 'Create an account', max: 50 },
  'password.toForgot': { en: 'Forgot your password?', max: 50 },
  'password.backToSignIn': { en: 'Back to sign in', max: 50 },
  'password.forgot.title': { en: 'Reset your password', max: 60 },
  'password.forgot.whatsappBody': { en: 'Send the message from the WhatsApp number on your account. We’ll reply in that chat with a link for choosing a new password — if you asked a moment ago, use the link we already sent.', max: 300 },
  'password.forgot.whatsappCta': { en: 'Message us on WhatsApp', max: 50 },
  'password.forgot.emailBody': { en: 'Enter your email address and we’ll send a link for choosing a new password.', max: 200 },
  'password.forgot.send': { en: 'Send reset link', max: 40 },
  'password.forgot.sent': { en: 'If an account exists for that address, a link is on its way.', max: 160 },
  'password.forgot.noneBody': { en: 'Password reset isn’t available online yet. Sign in another way, or contact us and we’ll help.', max: 240 },
  'reset.heading.title': { en: 'Choose a new password', max: 80 },
  'reset.heading.titleSet': { en: 'Choose a password', max: 80 },
  'reset.heading.lede': { en: 'You’ll be signed in as soon as it’s saved.', max: 160 },
  'reset.form.checking': { en: 'Checking your link…', max: 60 },
  'reset.form.label': { en: 'New password', max: 40 },
  'reset.form.submit': { en: 'Save password', max: 40 },
  'reset.form.saving': { en: 'Saving…', max: 40 },
  'reset.form.unreachable': { en: 'We couldn’t check your link. Check your connection and try again.', max: 160 },
  'reset.expired.title': { en: 'This link has expired', max: 80 },
  'reset.expired.body': { en: 'Reset links work once, and only for a short time. If you already chose a new password, sign in with it. Otherwise ask for a new link from the sign-in page.', max: 280 },
  'verifyEmail.heading.title': { en: 'Confirm your email', max: 80 },
  'verifyEmail.status.checking': { en: 'Confirming your email…', max: 60 },
  'verifyEmail.status.doneTitle': { en: 'Email confirmed', max: 80 },
  'verifyEmail.status.doneBody': { en: 'That address is now verified on your account.', max: 160 },
  'verifyEmail.status.invalidTitle': { en: 'This link has expired', max: 80 },
  'verifyEmail.status.invalidBody': { en: 'Verification links work once, and only for a short time. Ask for a new one from your profile.', max: 200 },
  'verifyEmail.status.otherTitle': { en: 'This link is for a different account', max: 80 },
  'verifyEmail.status.otherBody': { en: 'Sign in with the account the email was sent for, then open the link again.', max: 200 },
  'verifyEmail.status.errorTitle': { en: 'We couldn’t confirm your email', max: 80 },
  'verifyEmail.status.toProfile': { en: 'Go to your profile', max: 50 },
  'access.eyebrow': { en: 'Private shop', max: 40 },
  'access.defaultMessage': { en: 'This shop is private. Get in touch if you’d like access.', max: 200 },
  'access.signInLede': { en: 'Sign in to view the shop.', max: 120 },
  'access.registrationClosed': { en: 'New accounts aren’t being opened right now.', max: 160 },
  'access.myOrders': { en: 'My orders', max: 40 },
  'access.checkAgain': { en: 'Check again', max: 40 },
  'access.signOut': { en: 'Sign out', max: 40 },
  'access.contactAriaLabel': { en: 'Contact the shop', max: 60 },
  'code.error.tooMany': { en: 'Too many tries. Please wait a few minutes', max: 120 },
  'code.error.channelWhatsapp': { en: 'We couldn’t send a WhatsApp message to that number. Try a text message instead', max: 200 },
  'code.error.channelSms': { en: 'We couldn’t send a text message to that number. Try WhatsApp instead', max: 200 },
  'code.error.cannotSwitch': { en: 'We can’t send the code that way to this number', max: 160 },
  'code.error.expired': { en: 'That code has expired. We can send a new one', max: 160 },
  'code.error.incorrect': { en: { one: 'That code isn’t right. {count} try left.', other: 'That code isn’t right. {count} tries left.' }, max: 120 },
  'code.error.incorrectNoCount': { en: 'That code isn’t right.', max: 100 },
  'code.error.unavailable': { en: 'Sign-in by code isn’t working right now. Please try another way', max: 200 },
  'code.enter.label': { en: '6-digit code', max: 40 },
  'code.phone.country': { en: 'Country', max: 40 },
  'code.phone.chooseCountry': { en: 'Choose a country', max: 60 },
  'code.phone.suggested': { en: 'Suggested', max: 40 },
  'code.phone.allCountries': { en: 'All countries', max: 40 },
  'code.phone.number': { en: 'Phone number', max: 40 },
  'code.enter.title': { en: 'Enter your code', max: 60 },
  'code.enter.body': { en: 'Enter the 6-digit code we sent to {to} by {channel}.', max: 200 },
  'code.channel.whatsapp': { en: 'WhatsApp', max: 30 },
  'code.channel.sms': { en: 'text message', max: 30 },
  'code.channel.email': { en: 'email', max: 30 },
  'code.resend': { en: 'Resend code', max: 40 },
  'code.resendIn': { en: 'Resend code in {time}', max: 60 },
  'code.switchSms': { en: 'Didn’t get it? Send by text message instead', max: 100 },
  'code.switchWhatsapp': { en: 'Didn’t get it? Send by WhatsApp instead', max: 100 },
  'code.differentNumber': { en: 'Use a different number', max: 50 },
  'code.differentEmail': { en: 'Use a different email', max: 50 },
  'code.sentAgain': { en: 'We sent a new code.', max: 80 },
  'code.error.sendNew': { en: 'Send a new code', max: 40 },
  'code.phone.countryRequired': { en: 'Choose your country', max: 60 },
  'code.choose.phone': { en: 'Continue with phone number', max: 60 },
  'code.choose.email': { en: 'Continue with email', max: 60 },
  'code.choose.newHere': { en: 'New here? You’ll create your account as you sign in.', max: 120 },
  'code.back': { en: 'Choose another way', max: 50 },
  'code.phone.title': { en: 'Your phone number', max: 60 },
  'code.phone.sendWhatsapp': { en: 'Send code by WhatsApp', max: 50 },
  'code.phone.sendSms': { en: 'Send code by text message', max: 50 },
  'code.phone.whatsappBody': { en: 'Send us a message on WhatsApp and you’re signed in.', max: 160 },
  'code.email.title': { en: 'Your email', max: 60 },
  'code.email.continue': { en: 'Continue', max: 40 },
  'code.password.title': { en: 'Welcome back', max: 60 },
  'code.password.body': { en: 'Enter the password for {email}.', max: 120 },
  'code.password.emailCode': { en: 'Email me a code instead', max: 60 },
  'code.forgot.body': { en: 'We’ll email a link for choosing a new password to {email}.', max: 160 },
});
