import { defineTextArea } from '@/text/define.ts';

/** Area `checkout`: the checkout steps and their field errors (editable-text spec §6.1). */
export default defineTextArea('checkout', {
  'errors.required': { en: 'Required', max: 60 },
  'errors.paymentMissing': { en: 'Choose how you’d like to pay', max: 80 },
  'errors.emailInvalid': { en: 'Valid email required', max: 80 },
  'errors.contactMissing': { en: 'Email or phone is required', max: 80 },
  'errors.countryMissing': { en: 'Select your country', max: 80 },
  'errors.shippingMissing': { en: 'Choose a shipping method', max: 80 },
  'errors.coinMissing': { en: 'Choose a coin and network', max: 80 },
  'errors.stillPricing': { en: 'Still pricing your order — one moment', max: 100 },
  'errors.shippingStale': { en: 'That delivery option is no longer available — choose another', max: 120 },
  'errors.methodStale': { en: 'That payment method is no longer available — choose another', max: 120 },
  'errors.comboStale': { en: 'That coin and network are no longer available — choose another', max: 120 },
  'errors.unknownCode': { en: 'Unknown code', max: 60 },
  'errors.verifyBrowser': { en: "We couldn't verify your browser", max: 100 },
  'errors.verifyFailed': { en: "We couldn't verify your browser — please try again", max: 120 },
  'errors.placeFailed': { en: "We couldn't place your order", max: 100 },
  'errors.inProgress': { en: 'Checkout already in progress', max: 100 },

  'page.eyebrow': { en: 'Checkout', max: 40 },
  'page.title': { en: 'Checkout', max: 60 },
  'page.guestTitle': { en: 'Guest checkout', max: 60 },
  'page.guestUnavailableTitle': { en: "Guest checkout isn't available right now", max: 100 },
  'page.guestUnavailableBody': { en: "Sign in and we'll pick your order up from here.", max: 160 },
  'page.emptyTitle': { en: "There's nothing to check out", max: 80 },
  'page.emptyBody': { en: "Add something to your cart and we'll pick this back up.", max: 160 },
  'page.verifying': { en: 'Verifying…', max: 40 },
  'page.terms': { en: 'Placing the order confirms the details above. We’ll send you a link to track it.' },

  'steps.contact': { en: 'Contact', max: 30 },
  'steps.contactTitle': { en: 'Your details', max: 60 },
  'steps.address': { en: 'Address', max: 30 },
  'steps.addressTitle': { en: 'Delivery address', max: 60 },
  'steps.shipping': { en: 'Shipping', max: 30 },
  'steps.shippingTitle': { en: 'Delivery and discounts', max: 60 },
  'steps.payment': { en: 'Payment', max: 30 },
  'steps.paymentTitle': { en: 'How you’ll pay', max: 60 },
  'steps.review': { en: 'Review', max: 30 },
  'steps.reviewTitle': { en: 'Review your order', max: 60 },
  'steps.count': { en: 'Step {current} of {total}', max: 60 },

  'actions.continue': { en: 'Continue', max: 40 },
  'actions.back': { en: 'Back', max: 40 },
  'actions.placing': { en: 'Placing order…', max: 40 },
  'actions.placeOrder': { en: 'Place order', max: 40 },
  'actions.placeOrderTotal': { en: 'Place order · {total}', max: 60 },

  'address.blurb': { en: 'Where should we send it?', max: 100 },
  'address.line1': { en: 'Address line 1', max: 40 },
  'address.line2': { en: 'Address line 2', max: 40 },
  'address.line3': { en: 'Address line 3', max: 40 },
  'address.city': { en: 'City', max: 40 },
  'address.zip': { en: 'Postal code', max: 40 },
  'address.county': { en: 'State / Region', max: 40 },
  'address.townCity': { en: 'Town / City', max: 40 },
  'address.countyPlain': { en: 'County', max: 40 },
  'address.postcode': { en: 'Postcode', max: 40 },
  'address.eircode': { en: 'Eircode', max: 40 },
  'address.state': { en: 'State', max: 40 },
  'address.zipCode': { en: 'ZIP code', max: 40 },
  'address.province': { en: 'Province', max: 40 },
  'address.suburb': { en: 'Suburb', max: 40 },
  'address.country': { en: 'Country', max: 40 },
  'address.chooseCountry': { en: 'Choose a country', max: 40 },

  'contact.blurbEmail': { en: 'Order updates and the receipt go to this email.', max: 120 },
  'contact.blurbNoEmail': { en: 'Who is this order for?', max: 120 },
  'contact.firstName': { en: 'First name', max: 40 },
  'contact.surname': { en: 'Surname', max: 40 },
  'contact.email': { en: 'Email', max: 40 },
  'contact.haveAccount': { en: 'Have an account? {signIn} to use your saved details and store credit.' },

  'field.optional': { en: 'Optional', max: 30 },

  'phone.codeAriaLabel': { en: 'Phone country code', max: 60 },
  'phone.code': { en: 'Code', max: 20 },
  'phone.label': { en: 'Phone', max: 40 },
  'phone.hint': { en: 'Couriers may use this for delivery.', max: 120 },

  'coupon.codeLabel': { en: 'Coupon code', max: 40 },
  'coupon.placeholder': { en: 'Have a code?', max: 40 },
  'coupon.checking': { en: 'Checking', max: 30 },
  'coupon.apply': { en: 'Apply', max: 30 },
  'coupon.discountLabel': { en: 'Discount', max: 40 },
  'coupon.notApplied': { en: 'Not applied', max: 40 },
  'coupon.remove': { en: 'Remove', max: 30 },
  'coupon.autoApplied': { en: 'Applied automatically', max: 60 },
  'coupon.useAnother': { en: 'Use another', max: 40 },

  'crypto.coins': { en: 'Coins', max: 30 },
  'crypto.stablecoins': { en: 'Stablecoins', max: 30 },

  'quote.pricing': { en: 'Pricing your order…', max: 60 },

  'shipping.heading': { en: 'Delivery', max: 40 },
  'shipping.unserviceable': { en: 'We can’t ship to {country} yet. Choose another country, or message us and we’ll sort it.' },
  'shipping.thatCountry': { en: 'that country', max: 40 },
  'shipping.free': { en: 'Free', max: 30 },

  'payment.useStoreCredit': { en: 'Use store credit', max: 40 },
  'payment.creditAvailable': { en: '{amount} available', max: 60 },
  'payment.allCovered': { en: 'Nothing left to pay — store credit covers this order.', max: 120 },
  'payment.noMethods': { en: 'No payment method is available right now. Message us and we’ll take it from here.' },
  'payment.methodHeading': { en: 'Payment method', max: 40 },
  'payment.fee': { en: 'Fee', max: 30 },
  'payment.offlineNote': { en: 'We’ll send the transfer details once the order is placed.', max: 120 },

  'review.blurb': { en: 'One last look before we place it.', max: 100 },
  'review.change': { en: 'Change', max: 30 },
  'review.notChosen': { en: 'Not chosen', max: 40 },
  'review.notes': { en: 'Order notes', max: 40 },
  'review.notesPlaceholder': { en: 'Anything the courier or our packing team should know', max: 120 },

  'summary.ariaLabel': { en: 'Order summary', max: 40 },
  'summary.hide': { en: 'Hide summary', max: 40 },
  'summary.heading': { en: 'Your order', max: 40 },
  'summary.bulk': { en: 'Bulk', max: 20 },
  'summary.discountCode': { en: 'Discount {code}', max: 60 },
  'summary.nothingToPay': { en: 'Nothing to pay', max: 40 },
  'summary.toPay': { en: 'To pay', max: 40 },
  'summary.amountDue': { en: 'Amount due', max: 40 },
  'summary.creditCovers': { en: 'Store credit covers this order.', max: 100 },
  'summary.pending': { en: 'Shipping and discounts are added once we have your address.', max: 120 },
});
