import { defineTextArea } from '@/text/define.ts';

/** Area `checkout`: the checkout steps and their field errors (editable-text spec §6.1). */
export default defineTextArea('checkout', {
  'errors.required': { en: 'Required', note: 'Under a checkout (or verification) field left empty', max: 60 },
  'errors.paymentMissing': { en: 'Choose how you’d like to pay', note: 'Checkout payment step, when Continue is pressed with no method chosen', max: 80 },
  'errors.emailInvalid': { en: 'Valid email required', note: 'Under the checkout email field, when the address is not a valid email', max: 80 },
  'errors.contactMissing': { en: 'Email or phone is required', note: 'Under the guest checkout email field, when neither email nor phone is filled in', max: 80 },
  'errors.countryMissing': { en: 'Select your country', note: 'Under the checkout country picker, when no country is chosen', max: 80 },
  'errors.shippingMissing': { en: 'Choose a shipping method', note: 'Checkout delivery step, when Continue is pressed with no delivery option chosen', max: 80 },
  'errors.coinMissing': { en: 'Choose a coin and network', note: 'Checkout payment step, when crypto is chosen without a coin and network', max: 80 },
  'errors.stillPricing': { en: 'Still pricing your order — one moment', note: 'Checkout delivery and payment steps, when Continue is pressed before the order is priced', max: 100 },
  'errors.shippingStale': { en: 'That delivery option is no longer available — choose another', note: 'Checkout delivery step, when the chosen delivery option has been withdrawn', max: 120 },
  'errors.methodStale': { en: 'That payment method is no longer available — choose another', note: 'Checkout payment step, when the chosen payment method has been withdrawn', max: 120 },
  'errors.comboStale': { en: 'That coin and network are no longer available — choose another', note: 'Checkout payment step, when the chosen coin and network have been withdrawn', max: 120 },
  'errors.unknownCode': { en: 'Unknown code', note: 'Under the coupon field, when the code entered does not exist', max: 60 },
  'errors.verifyBrowser': { en: "We couldn't verify your browser", note: 'Top of guest checkout, when the invisible bot check fails (with a Try again button)', max: 100 },
  'errors.verifyFailed': { en: "We couldn't verify your browser — please try again", note: 'Guest checkout, when the invisible bot check fails or times out', max: 120 },
  'errors.placeFailed': { en: "We couldn't place your order", note: 'Top of the checkout, when placing the order fails without a reason from the shop', max: 100 },
  'errors.inProgress': { en: 'Checkout already in progress', note: 'Pop-up message when the order is placed twice at the same time', max: 100 },

  'page.eyebrow': { en: 'Checkout', note: 'Small label above the checkout heading and the checkout notices', max: 40 },
  'page.title': { en: 'Checkout', note: 'Checkout page heading for a signed-in shopper', max: 60 },
  'page.guestTitle': { en: 'Guest checkout', note: 'Checkout page heading for a shopper who is not signed in', max: 60 },
  'page.guestUnavailableTitle': { en: "Guest checkout isn't available right now", note: 'Checkout page heading when guest checkout is switched on but cannot run', max: 100 },
  'page.guestUnavailableBody': { en: "Sign in and we'll pick your order up from here.", note: 'Line under "Guest checkout isn\'t available right now"', max: 160 },
  'page.emptyTitle': { en: "There's nothing to check out", note: 'Checkout page heading when the cart is empty', max: 80 },
  'page.emptyBody': { en: "Add something to your cart and we'll pick this back up.", note: 'Line under "There\'s nothing to check out"', max: 160 },
  'page.verifying': { en: 'Verifying…', note: 'Guest checkout, while the invisible bot check runs', max: 40 },
  'page.terms': { en: 'Placing the order confirms the details above. We’ll send you a link to track it.', note: 'Small print under the Place order button on the review step' },

  'steps.contact': { en: 'Contact', note: 'Name of the first checkout step, in the step bar and on the review step', max: 30 },
  'steps.contactTitle': { en: 'Your details', note: 'Heading of the first checkout step', max: 60 },
  'steps.address': { en: 'Address', note: 'Name of the address step in the checkout step bar', max: 30 },
  'steps.addressTitle': { en: 'Delivery address', note: 'Heading of the address step, and its box on the review step', max: 60 },
  'steps.shipping': { en: 'Shipping', note: 'Name of the delivery step, in the step bar and on the review step', max: 30 },
  'steps.shippingTitle': { en: 'Delivery and discounts', note: 'Heading of the delivery step', max: 60 },
  'steps.payment': { en: 'Payment', note: 'Name of the payment step, in the step bar and on the review step', max: 30 },
  'steps.paymentTitle': { en: 'How you’ll pay', note: 'Heading of the payment step', max: 60 },
  'steps.review': { en: 'Review', note: 'Name of the last checkout step in the step bar', max: 30 },
  'steps.reviewTitle': { en: 'Review your order', note: 'Heading of the last checkout step', max: 60 },
  'steps.count': { en: 'Step {current} of {total}', note: 'Above each checkout step heading; {current} is the step number, {total} the number of steps', max: 60 },

  'actions.continue': { en: 'Continue', note: 'Checkout button that moves on to the next step', max: 40 },
  'actions.back': { en: 'Back', note: 'Checkout button that goes back one step', max: 40 },
  'actions.placing': { en: 'Placing order…', note: 'Place order button while the order is being placed', max: 40 },
  'actions.placeOrder': { en: 'Place order', note: 'Button on the review step when there is nothing to pay', max: 40 },
  'actions.placeOrderTotal': { en: 'Place order · {total}', note: 'Button on the review step; {total} is the amount to pay', max: 60 },

  'address.blurb': { en: 'Where should we send it?', note: 'Line at the top of the address step', max: 100 },
  'address.line1': { en: 'Address line 1', note: 'Address step field label', max: 40 },
  'address.line2': { en: 'Address line 2', note: 'Address step field label (optional field)', max: 40 },
  'address.city': { en: 'City', note: 'Address step field label', max: 40 },
  'address.zip': { en: 'ZIP / Postcode', note: 'Address step field label', max: 40 },
  'address.county': { en: 'County / Region', note: 'Address step field label (optional field)', max: 40 },
  'address.country': { en: 'Country', note: 'Label of the country picker', max: 40 },
  'address.chooseCountry': { en: 'Choose a country', note: 'First, empty choice in the country picker', max: 40 },

  'contact.blurbEmail': { en: 'Order updates and the receipt go to this email.', note: 'Line at the top of the contact step when the shop asks for an email', max: 120 },
  'contact.blurbNoEmail': { en: 'Who is this order for?', note: 'Line at the top of the contact step when the shop does not ask for an email', max: 120 },
  'contact.firstName': { en: 'First name', note: 'Contact step field label', max: 40 },
  'contact.surname': { en: 'Surname', note: 'Contact step field label', max: 40 },
  'contact.email': { en: 'Email', note: 'Contact step field label', max: 40 },
  'contact.haveAccount': { en: 'Have an account? {signIn} to use your saved details and store credit.', note: 'Guest checkout contact step; {signIn} is the Sign in link' },

  'field.optional': { en: 'Optional', note: 'Small tag beside an optional checkout field label', max: 30 },

  'phone.codeAriaLabel': { en: 'Phone country code', note: 'Screen-reader label of the dial-code picker', max: 60 },
  'phone.code': { en: 'Code', note: 'Label of the dial-code picker, and its empty choice', max: 20 },
  'phone.label': { en: 'Phone', note: 'Contact step phone field label', max: 40 },
  'phone.hint': { en: 'Couriers may use this for delivery.', note: 'Small line under the phone field', max: 120 },

  'coupon.codeLabel': { en: 'Coupon code', note: 'Label of the coupon field on the delivery step', max: 40 },
  'coupon.placeholder': { en: 'Have a code?', note: 'Placeholder inside the coupon field', max: 40 },
  'coupon.checking': { en: 'Checking', note: 'Coupon Apply button while the code is checked', max: 30 },
  'coupon.apply': { en: 'Apply', note: 'Coupon field button', max: 30 },
  'coupon.discountLabel': { en: 'Discount', note: 'Label over a coupon code that is on the order (or was turned down)', max: 40 },
  'coupon.notApplied': { en: 'Not applied', note: 'Beside a coupon code the shop turned down without a reason', max: 40 },
  'coupon.remove': { en: 'Remove', note: 'Button that takes a coupon code off the order', max: 30 },
  'coupon.autoApplied': { en: 'Applied automatically', note: 'Beside a discount the shop applied on its own', max: 60 },
  'coupon.useAnother': { en: 'Use another', note: 'Button to enter a different code over an automatic discount', max: 40 },

  'crypto.coins': { en: 'Coins', note: 'Group heading in the crypto coin and network picker', max: 30 },
  'crypto.stablecoins': { en: 'Stablecoins', note: 'Group heading in the crypto coin and network picker', max: 30 },

  'quote.pricing': { en: 'Pricing your order…', note: 'Delivery and payment steps, while the order is being priced', max: 60 },

  'shipping.heading': { en: 'Delivery', note: 'Heading over the delivery options', max: 40 },
  'shipping.unserviceable': { en: 'We can’t ship to {country} yet. Choose another country, or message us and we’ll sort it.', note: 'Delivery step, when there are no delivery options for the address; {country} is the country name' },
  'shipping.thatCountry': { en: 'that country', note: 'Stands in for {country} in "We can’t ship to {country} yet" when the country has no name', max: 40 },
  'shipping.free': { en: 'Free', note: 'Price of a free delivery option, and the shipping row of the order summary', max: 30 },

  'payment.useStoreCredit': { en: 'Use store credit', note: 'Payment step checkbox for a signed-in shopper with a balance', max: 40 },
  'payment.creditAvailable': { en: '{amount} available', note: 'Beside "Use store credit"; {amount} is the balance', max: 60 },
  'payment.allCovered': { en: 'Nothing left to pay — store credit covers this order.', note: 'Payment step, when store credit pays for the whole order', max: 120 },
  'payment.noMethods': { en: 'No payment method is available right now. Message us and we’ll take it from here.', note: 'Payment step, when the shop offers no way to pay' },
  'payment.methodHeading': { en: 'Payment method', note: 'Heading over the payment methods', max: 40 },
  'payment.fee': { en: 'Fee', note: 'Beside a payment method\'s fee rate when the method has no fee name of its own', max: 30 },
  'payment.offlineNote': { en: 'We’ll send the transfer details once the order is placed.', note: 'Payment step, under a bank-transfer style method', max: 120 },

  'review.blurb': { en: 'One last look before we place it.', note: 'Line at the top of the review step', max: 100 },
  'review.change': { en: 'Change', note: 'Button on each review-step box that goes back to that step', max: 30 },
  'review.notChosen': { en: 'Not chosen', note: 'Review step, for a delivery option or payment method not yet chosen', max: 40 },
  'review.notes': { en: 'Order notes', note: 'Review step notes field label', max: 40 },
  'review.notesPlaceholder': { en: 'Anything the courier or our packing team should know', note: 'Placeholder inside the order notes field', max: 120 },

  'summary.ariaLabel': { en: 'Order summary', note: 'Order summary beside the checkout: its screen-reader name, and the phone toggle while closed', max: 40 },
  'summary.hide': { en: 'Hide summary', note: 'Phone toggle of the order summary while open', max: 40 },
  'summary.heading': { en: 'Your order', note: 'Heading of the order summary beside the checkout', max: 40 },
  'summary.bulk': { en: 'Bulk', note: 'Tag on a summary line priced at a bulk tier', max: 20 },
  'summary.discountCode': { en: 'Discount {code}', note: 'Order summary discount row; {code} is the coupon code', max: 60 },
  'summary.nothingToPay': { en: 'Nothing to pay', note: 'Order summary\'s final figure label when store credit covers it', max: 40 },
  'summary.toPay': { en: 'To pay', note: 'Order summary\'s final figure label once a payment method is chosen', max: 40 },
  'summary.amountDue': { en: 'Amount due', note: 'Order summary row and final figure label before a payment method is chosen', max: 40 },
  'summary.creditCovers': { en: 'Store credit covers this order.', note: 'Under the order summary when store credit pays for everything', max: 100 },
  'summary.pending': { en: 'Shipping and discounts are added once we have your address.', note: 'Under the order summary before an address is entered', max: 120 },
});
