import { defineTextArea } from '@/text/define.ts';

/** Area `common`: the same wording for the same purpose in several areas (spec §6.1 "one key per meaning"). */
export default defineTextArea('common', {
  'actions.tryAgain': { en: 'Try again', note: 'Retry button on error screens across the shop', max: 40 },
  'actions.copy': { en: 'Copy', note: 'Copy-to-clipboard button', max: 30 },
  'actions.copied': { en: 'Copied', note: 'Copy button, just after copying', max: 30 },
  'actions.browseCatalogue': { en: 'Browse the catalogue', note: 'Button on the empty cart, empty checkout and empty order history', max: 60 },
  'actions.backToShop': { en: '← Back to shop', note: 'Link back to the catalogue on order, payment and verification pages', max: 60 },
  'actions.close': { en: 'Close', note: 'Screen-reader label of the close (×) button on drawers and sheets', max: 40 },
  'actions.signIn': { en: 'Sign in', note: 'Sign-in button, and the header account button when signed out', max: 40 },
  'actions.cancel': { en: 'Cancel', note: 'Button that backs out of a confirmation (loyalty redemption, switching to the classic bot)', max: 30 },
  'status.loading': { en: 'Loading', note: 'Screen-reader label while a page or list loads', max: 40 },
  'status.checking': { en: 'Checking…', note: 'Button label while a code, reference or transaction is being checked', max: 40 },
  'product.preorder': { en: 'Pre-order', note: 'Tag on pre-order products, cart lines and order items', max: 30 },
  'qty.fewer': { en: 'One fewer {name}', note: 'Screen-reader label of the − quantity button; {name} is the product', max: 120 },
  'qty.more': { en: 'One more {name}', note: 'Screen-reader label of the + quantity button; {name} is the product', max: 120 },
  'qty.remove': { en: 'Remove {name}', note: 'Screen-reader label of a line\'s remove button; {name} is the product', max: 120 },
  'totals.subtotal': { en: 'Subtotal', note: 'Row label in the cart, checkout, order and account totals', max: 40 },
  'totals.total': { en: 'Total', note: 'Row label for the order total', max: 40 },
  'totals.discount': { en: 'Discount', note: 'Row label for a discount in order totals', max: 40 },
  'totals.shipping': { en: 'Shipping', note: 'Row label for shipping in order totals', max: 40 },
  'totals.paymentFee': { en: 'Payment fee', note: 'Row label for a payment-method fee', max: 40 },
  'totals.storeCredit': { en: 'Store credit', note: 'Row label for store credit applied or held', max: 40 },
  'nav.yourAccount': { en: 'Your account', note: 'Header account button when signed in, and the account page heading fallback', max: 40 },
  'list.loadFailed': { en: "We couldn't load the products", note: 'Catalogue and trade list, when the product list fails to load', max: 80 },
  'list.categoryMissing': { en: "That category isn't here", note: 'Catalogue and trade list, for an unknown category link', max: 80 },
  'list.noMatches': { en: 'Nothing matches "{query}"', note: 'Catalogue and trade list, when a search finds nothing', max: 80 },
  'list.clearSearch': { en: 'Clear search', note: 'Button under "Nothing matches"', max: 40 },
  'list.emptyCategory': { en: 'Nothing stocked here yet', note: 'Catalogue and trade list, for a category with no products', max: 80 },
  'contact.whatsapp': { en: 'WhatsApp', note: 'Contact-link and sign-in channel name', max: 30 },
  'contact.telegram': { en: 'Telegram', note: 'Contact-link and sign-in channel name', max: 30 },
  'video.title': { en: 'Video', note: 'Screen-reader name of an embedded video that has no title of its own', max: 60 },
});
