import { defineTextArea } from '@/text/define.ts';

/** Area `common`: the same wording for the same purpose in several areas (spec §6.1 "one key per meaning"). */
export default defineTextArea('common', {
  'actions.tryAgain': { en: 'Try again', max: 40 },
  'actions.copy': { en: 'Copy', max: 30 },
  'actions.copied': { en: 'Copied', max: 30 },
  'actions.browseCatalogue': { en: 'Browse the catalogue', max: 60 },
  'actions.backToShop': { en: '← Back to shop', max: 60 },
  'actions.close': { en: 'Close', max: 40 },
  'actions.signIn': { en: 'Sign in', max: 40 },
  'actions.cancel': { en: 'Cancel', max: 30 },
  'status.loading': { en: 'Loading', max: 40 },
  'status.checking': { en: 'Checking…', max: 40 },
  'product.preorder': { en: 'Pre-order', max: 30 },
  'qty.fewer': { en: 'One fewer {name}', max: 120 },
  'qty.more': { en: 'One more {name}', max: 120 },
  'qty.remove': { en: 'Remove {name}', max: 120 },
  'totals.subtotal': { en: 'Subtotal', max: 40 },
  'totals.total': { en: 'Total', max: 40 },
  'totals.discount': { en: 'Discount', max: 40 },
  'totals.shipping': { en: 'Shipping', max: 40 },
  'totals.paymentFee': { en: 'Payment fee', max: 40 },
  'totals.storeCredit': { en: 'Store credit', max: 40 },
  'nav.yourAccount': { en: 'Your account', max: 40 },
  'list.loadFailed': { en: "We couldn't load the products", max: 80 },
  'list.categoryMissing': { en: "That category isn't here", max: 80 },
  'list.noMatches': { en: 'Nothing matches "{query}"', max: 80 },
  'list.clearSearch': { en: 'Clear search', max: 40 },
  'list.emptyCategory': { en: 'Nothing stocked here yet', max: 80 },
  'contact.whatsapp': { en: 'WhatsApp', max: 30 },
  'contact.telegram': { en: 'Telegram', max: 30 },
  'video.title': { en: 'Video', max: 60 },
});
