import { defineTextArea } from '@/text/define.ts';

/** Area `product`: product cards, rows and product pages (editable-text spec §6.1). */
export default defineTextArea('product', {
  'stock.in': { en: 'In Stock', note: 'Stock chip on product cards and pages', max: 30 },
  'stock.low': { en: 'Low Stock', note: 'Stock chip when stock is low', max: 30 },
  'stock.out': { en: 'Out of Stock', note: 'Stock chip when sold out', max: 30 },
  'limit.min': { en: 'Min {min}', note: 'Minimum order quantity flag on product cards, rows and pages', max: 30 },
  'add.verb': { en: 'Add', note: "Start of the add-to-cart button label (\"Add 2 · $10.00\") and of a row's screen-reader label", max: 30 },
  'add.unavailable': { en: 'Unavailable', note: "Add-to-cart button label for a product that can't be ordered", max: 30 },
  'add.outOfStock': { en: 'Out of stock', note: 'Add-to-cart button label when the product is sold out', max: 30 },
  'add.added': { en: 'Added', note: 'Add-to-cart button label for a moment after adding', max: 30 },
  'add.another': { en: 'Add another', note: 'Add-to-cart button label once a product has been added', max: 30 },
  'add.labelWithName': { en: '{label} — {name}', note: 'Screen-reader label of an icon-only add button: its label, then the product name', max: 80 },
  'add.ariaLabel': { en: '{verb} {name}', note: "Screen-reader label of a product row's quick-add button", max: 80 },
  'row.unavailable': { en: 'Unavailable — {name}', note: "Screen-reader label of a product row's add button when the product can't be ordered", max: 80 },
  'row.outOfStock': { en: 'Out of stock — {name}', note: "Screen-reader label of a product row's add button when sold out", max: 80 },
  'detail.breadcrumb': { en: 'Breadcrumb', note: 'Screen-reader name of the trail above a product page', max: 40 },
  'detail.shop': { en: 'Shop', note: 'First step of the breadcrumb on a product page (back to the catalogue)', max: 30 },
  'detail.preorderShips': { en: 'Pre-order · ships {eta}', note: 'Pre-order flag on a product page when a ship date is set', max: 60 },
  'detail.product': { en: 'Product', note: "Small label above the \"product not found\" message, and the product sheet's fallback title", max: 40 },
  'detail.notFoundTitle': { en: "We can't find that product", note: "Heading when a product page can't be loaded", max: 80 },
  'detail.notFoundDetail': { en: 'It may have sold out and been retired, or the link may be out of date.', note: "Explanation under the \"can't find that product\" heading" },
  'detail.browse': { en: 'Browse the shop', note: "Button on the \"can't find that product\" message", max: 40 },
  'bulk.heading': { en: 'Buy more, pay less', note: 'Heading of the quantity price ladder on a product', max: 60 },
  'bulk.quantity': { en: 'Quantity', note: 'Column heading of the quantity price ladder', max: 30 },
  'bulk.unitPrice': { en: 'Unit price', note: 'Column heading of the quantity price ladder', max: 30 },
  'bulk.saving': { en: 'Saving', note: 'Column heading of the quantity price ladder', max: 30 },
  'provenance.heading': { en: 'Provenance', note: "Heading above a product's provenance note", max: 40 },
  'ask.heading': { en: 'Ask first', note: 'Heading of the "message us about this product" block', max: 40 },
  'ask.text': { en: "Send us a message about {name} and we'll answer before you order.", note: 'Invitation to message the shop about a product' },
  'ask.prefill': { en: 'Hi — a question about {name} ({sku})', note: 'Text pre-filled in the chat when a shopper taps WhatsApp or Telegram on a product', max: 120 },
  'sheet.ships': { en: 'Ships {eta}', note: 'Pre-order flag in the product sheet when a ship date is set', max: 60 },
  'sheet.loadFailed': { en: "We couldn't load this product.", note: 'Message in the product sheet when loading fails', max: 80 },
  'sheet.unit': { en: 'Unit', note: 'Label beside the price in the product sheet', max: 30 },
  'sheet.description': { en: 'Description', note: "Heading of a product's description in the sheet", max: 40 },
  'upsells.heading': { en: 'Often bought with this', note: 'Heading above suggested products on a product page', max: 60 },
});
