import { defineTextArea } from '@/text/define.ts';

/** Area `product`: product cards, rows and product pages (editable-text spec §6.1). */
export default defineTextArea('product', {
  'stock.in': { en: 'In Stock', max: 30 },
  'stock.low': { en: 'Low Stock', max: 30 },
  'stock.out': { en: 'Out of Stock', max: 30 },
  'limit.min': { en: 'Min {min}', max: 30 },
  'add.verb': { en: 'Add', max: 30 },
  'add.unavailable': { en: 'Unavailable', max: 30 },
  'add.added': { en: 'Added', max: 30 },
  'add.another': { en: 'Add another', max: 30 },
  'add.labelWithName': { en: '{label} — {name}', max: 80 },
  'add.ariaLabel': { en: '{verb} {name}', max: 80 },
  'row.unavailable': { en: 'Unavailable — {name}', max: 80 },
  'row.outOfStock': { en: 'Out of stock — {name}', max: 80 },
  'detail.breadcrumb': { en: 'Breadcrumb', max: 40 },
  'detail.shop': { en: 'Shop', max: 30 },
  'detail.preorderShips': { en: 'Pre-order · ships {eta}', max: 60 },
  'detail.product': { en: 'Product', max: 40 },
  'detail.notFoundTitle': { en: "We can't find that product", max: 80 },
  'detail.notFoundDetail': { en: 'It may have sold out and been retired, or the link may be out of date.' },
  'detail.browse': { en: 'Browse the shop', max: 40 },
  'bulk.heading': { en: 'Buy more, pay less', max: 60 },
  'bulk.quantity': { en: 'Quantity', max: 30 },
  'bulk.unitPrice': { en: 'Unit price', max: 30 },
  'bulk.saving': { en: 'Saving', max: 30 },
  'provenance.heading': { en: 'Provenance', max: 40 },
  'coa.heading': { en: 'Certificate of analysis', max: 60 },
  'coa.lab': { en: 'Lab', max: 30 },
  'coa.amount': { en: 'Amount', max: 30 },
  'coa.purity': { en: 'Purity', max: 30 },
  'coa.batch': { en: 'Batch', max: 30 },
  'coa.tested': { en: 'Tested', max: 30 },
  'coa.view': { en: 'View report', max: 30 },
  'coa.viewFrom': { en: 'View report from {lab}', max: 80 },
  'coa.viewNamed': { en: 'View report: {name}', max: 80 },
  'coa.report': { en: 'Report', max: 30 },
  'coa.previous': { en: 'Previous reports ({count})', max: 50 },
  'coa.newTab': { en: 'Opens in a new tab', max: 40 },
  'ask.heading': { en: 'Ask first', max: 40 },
  'ask.text': { en: "Send us a message about {name} and we'll answer before you order." },
  'ask.prefill': { en: 'Hi — a question about {name} ({sku})', max: 120 },
  'sheet.ships': { en: 'Ships {eta}', max: 60 },
  'sheet.loadFailed': { en: "We couldn't load this product.", max: 80 },
  'sheet.unit': { en: 'Unit', max: 30 },
  'sheet.description': { en: 'Description', max: 40 },
  'upsells.heading': { en: 'Often bought with this', max: 60 },
});
