import { defineTextArea } from '@/text/define.ts';

/** Area `tracking`: the order-tracking page (/tracking and /tracking/:reference). */
export default defineTextArea('tracking', {
  // ── lookup form + masthead ────────────────────────────────────────────────
  'lookup.eyebrow': { en: 'Delivery', note: 'Small label above the title on the order-tracking page', max: 40 },
  'lookup.title': { en: 'Track your order', note: 'Title of the order-tracking page', max: 80 },
  'lookup.lead': { en: 'See where your parcel is and every scan along the way.', note: 'Line under the title on the order-tracking page' },
  'lookup.strip': { en: 'Order tracking', note: 'Small heading on the strip above a tracking result', max: 40 },
  'lookup.another': { en: 'Track another →', note: 'Link above a tracking result that goes back to the lookup form', max: 40 },
  'lookup.label': { en: 'Order number', note: 'Label of the order-number box on the tracking lookup form', max: 40 },
  'lookup.placeholder': { en: 'A7K2QM', note: 'Example order number shown inside the empty lookup box', max: 40 },
  'lookup.hint': { en: 'Six characters, on your order confirmation.', note: 'Help line under the order-number box' },
  'lookup.submit': { en: 'Track order', note: 'Button that looks up the order', max: 40 },
  'lookup.recent': { en: 'Recent', note: 'Heading above the orders this browser looked at before', max: 40 },
  'lookup.invalidReference': { en: 'Check that reference', note: 'Error beside the order-number label when the number is not in the right shape', max: 60 },

  // ── hero (summary above the fold) ─────────────────────────────────────────
  'hero.summaryAria': { en: 'Order tracking summary', note: 'Screen-reader name of the summary block at the top of a tracking result', max: 80 },
  'hero.orderRef': { en: 'Order {reference}', note: 'Small line above the headline; {reference} is the order number', max: 60 },
  'hero.deliveredOn': { en: 'Delivered {date}', note: 'Line under the headline once a parcel is delivered; {date} is the delivery date', max: 60 },
  'hero.headingTo': { en: 'Heading to {place}', note: 'Where the parcel is going, under the headline and on each parcel card; {place} is the destination', max: 60 },
  'hero.parcelsDispatched': { en: '{count} parcels dispatched', note: 'Line under the headline when an order has several parcels', max: 60 },
  'hero.factPlaced': { en: 'Placed', note: 'Label of the date the order was placed, in the facts grid', max: 30 },
  'hero.factItems': { en: 'Items', note: 'Label of the item count in the facts grid', max: 30 },
  'hero.factLastScan': { en: 'Last scan', note: 'Label of the time of the latest courier scan, in the facts grid', max: 30 },
  'hero.factParcels': { en: 'Parcels', note: 'Label of the parcel count in the facts grid', max: 30 },
  'hero.factType': { en: 'Type', note: 'Label of the order type in the facts grid', max: 30 },

  // ── parcel card ───────────────────────────────────────────────────────────
  'parcel.title': { en: 'Parcel {index} of {count}', note: 'Heading of each parcel card on an order with several parcels', max: 60 },
  'parcel.single': { en: 'Parcel', note: 'Heading of the parcel card on an order with one parcel', max: 40 },
  'parcel.trackingNumber': { en: 'Tracking number', note: 'Label of the copyable tracking number on a parcel card', max: 40 },
  'parcel.carrierRef': { en: 'Carrier ref', note: 'Label of the courier’s own reference number on a parcel card', max: 40 },
  'parcel.trackWith': { en: 'Track with {carrier}', note: 'Link to the local carrier’s tracking page; {carrier} is its name', max: 60 },
  'parcel.awaitingScan': { en: 'Awaiting first scan', note: 'Small heading of the note on a parcel the courier has not scanned yet, and the stage name before any scan', max: 60 },
  'parcel.notFoundBody': { en: 'The label exists but the courier hasn\'t scanned this parcel yet. That\'s normal for the first day or so after dispatch — check back later.', note: 'Note on a parcel the courier has not scanned yet' },
  'parcel.errorEyebrow': { en: 'Carrier not responding', note: 'Small heading of the note when the courier could not be reached for this parcel', max: 60 },
  'parcel.errorBody': { en: 'The carrier isn\'t answering right now. Nothing is wrong with your parcel.', note: 'Note when the courier could not be reached for this parcel' },
  'parcel.lastKnown': { en: 'Last known', note: 'Small heading of the note on a parcel with a tracking number but no live tracking', max: 60 },
  'parcel.awaitingNumber': { en: 'Awaiting tracking number', note: 'Small heading of the note on a parcel with no tracking number yet', max: 60 },
  'parcel.unavailableBody': { en: 'Live tracking is unavailable right now. Search the tracking number above on your carrier’s website for the latest scan.', note: 'Note on a parcel that has a tracking number but no live tracking' },
  'parcel.noNumberBody': { en: 'This parcel doesn’t have a tracking number yet. One appears here as soon as the carrier issues it.', note: 'Note on a parcel that has no tracking number yet' },

  // ── scan timeline ─────────────────────────────────────────────────────────
  'timeline.title': { en: 'Scan history', note: 'Heading of the list of courier scans on a parcel', max: 40 },
  'timeline.count': { en: { one: '{count} scan', other: '{count} scans' }, note: 'Number of courier scans beside the Scan history heading', max: 40 },
  'timeline.noTimestamp': { en: 'No timestamp', note: 'Shown instead of a date on a courier scan that has none', max: 40 },

  // ── status labels ─────────────────────────────────────────────────────────
  'status.preTransit': { en: 'Label created', note: 'Parcel status: the shipping label exists but the parcel has not moved', max: 40 },
  'status.inTransit': { en: 'In transit', note: 'Parcel status: on its way', max: 40 },
  'status.customs': { en: 'In customs', note: 'Parcel status: held for customs', max: 40 },
  'status.outForDelivery': { en: 'Out for delivery', note: 'Parcel status: with the courier for delivery today', max: 40 },
  'status.availableForPickup': { en: 'Ready for pickup', note: 'Parcel status: waiting for the customer to collect it', max: 40 },
  'status.delivered': { en: 'Delivered', note: 'Parcel status: delivered', max: 40 },
  'status.exception': { en: 'Needs attention', note: 'Parcel status: the courier reported a problem', max: 40 },
  'status.returned': { en: 'Returned to sender', note: 'Parcel status: on its way back to the shop', max: 40 },
  'status.unknown': { en: 'Status unavailable', note: 'Parcel status shown when the courier status is not known', max: 40 },
  'status.stageOrdered': { en: 'Ordered', note: 'Progress rail stage 1 of 7', max: 30 },
  'status.stageCollected': { en: 'Collected', note: 'Progress rail stage 2 of 7', max: 30 },
  'status.stageInFlight': { en: 'In flight', note: 'Progress rail stage 3 of 7', max: 30 },
  'status.stageCustoms': { en: 'Customs', note: 'Progress rail stage 4 of 7', max: 30 },
  'status.stageLocalCarrier': { en: 'Local carrier', note: 'Progress rail stage 5 of 7', max: 30 },
  'status.stageOutForDelivery': { en: 'Out for delivery', note: 'Progress rail stage 6 of 7', max: 30 },
  'status.stageDelivered': { en: 'Delivered', note: 'Progress rail stage 7 of 7', max: 30 },
  'status.stageSummary': { en: 'Stage {stage} of {total}: {name}', note: 'Screen-reader sentence for the progress rail; {name} is the current stage name', max: 80 },
  'status.awaitingCourierScan': { en: 'Awaiting first courier scan', note: 'Screen-reader sentence for the progress rail before any courier scan', max: 80 },

  // ── relative times ────────────────────────────────────────────────────────
  'time.justNow': { en: 'just now', note: 'Relative time under a minute', max: 30 },
  'time.minutesAgo': { en: '{minutes} min ago', note: 'Relative time in minutes', max: 30 },
  'time.hoursAgo': { en: '{hours}h ago', note: 'Relative time in hours', max: 30 },
  'time.daysAgo': { en: { one: '1 day ago', other: '{count} days ago' }, note: 'Relative time in days', max: 30 },
  'time.unknown': { en: 'Date unknown', note: 'Shown when a scan or date cannot be read', max: 30 },

  // ── refresh control ───────────────────────────────────────────────────────
  'refresh.checked': { en: 'Checked {when}', note: 'Freshness line above the Refresh button; {when} is like "12 min ago"', max: 60 },
  'refresh.notChecked': { en: 'Not checked yet', note: 'Freshness line above the Refresh button before the courier was asked', max: 60 },
  'refresh.availableIn': { en: 'Refresh available in {countdown}', note: 'Screen-reader name of the Refresh button while it counts down; {countdown} is minutes and seconds', max: 80 },
  'refresh.label': { en: 'Refresh', note: 'Button that asks the courier for a fresh scan', max: 30 },

  // ── screens and notices ───────────────────────────────────────────────────
  'states.loading': { en: 'Loading tracking', note: 'Screen-reader name of the placeholder shown while tracking loads', max: 60 },
  'states.verifying': { en: 'Checking you\'re human', note: 'Line shown while the security check runs before a lookup', max: 60 },
  'states.blockedHead': { en: 'Verification unavailable', note: 'Heading when the security check never completed', max: 60 },
  'states.blockedBody': { en: 'We couldn\'t finish the security check that protects order lookups, so we can\'t fetch your tracking. A privacy extension or network filter blocking Cloudflare challenges is the usual cause.', note: 'Text when the security check never completed' },
  'states.reload': { en: 'Reload page', note: 'Button on the security-check-failed screen', max: 40 },
  'states.notFoundHead': { en: 'No order found', note: 'Heading when no order matches the number', max: 60 },
  'states.notFoundBody': { en: 'We couldn\'t find an order with that number. Check it against your confirmation — it\'s six characters, letters and numbers.', note: 'Text when no order matches the number' },
  'states.offHead': { en: 'Tracking unavailable', note: 'Heading when the shop has order tracking switched off', max: 60 },
  'states.offBody': { en: 'Order tracking isn\'t switched on right now. Message us with your order number and we\'ll look it up for you.', note: 'Text when the shop has order tracking switched off' },
  'states.rateHead': { en: 'Too many lookups', note: 'Heading when this connection has made too many lookups', max: 60 },
  'states.rateBody': { en: 'This connection has made a lot of lookups in the last few minutes. Wait a minute, then try again.', note: 'Text when this connection has made too many lookups' },
  'states.challengeHead': { en: 'Verification didn\'t go through', note: 'Heading when the security check was rejected', max: 60 },
  'states.challengeBody': { en: 'The security check that protects order lookups didn\'t complete. Try again — we\'ll run a fresh one.', note: 'Text when the security check was rejected' },
  'states.connectionHead': { en: 'Connection error', note: 'Heading when the tracking service could not be reached', max: 60 },
  'states.connectionBody': { en: 'We couldn\'t reach the tracking service. Try again in a moment.', note: 'Text when the tracking service could not be reached' },
  'states.thisOrder': { en: 'This order', note: 'Small heading on a cancelled or refunded order with no parcels', max: 40 },
  'states.noParcels': { en: 'No parcels yet', note: 'Small heading on an order with no parcels dispatched', max: 40 },
  'states.cancelledBody': { en: 'This order was {status}. Nothing will be dispatched.', note: 'Text on a cancelled or refunded order; {status} is the order status such as cancelled or refunded' },
  'states.preorderBody': { en: 'This is a pre-order, so it ships once stock lands. We\'ll send a tracking number then.', note: 'Text on a pre-order with nothing dispatched' },
  'states.notDispatchedBody': { en: 'Your order hasn\'t been dispatched yet. A tracking number appears here as soon as it\'s on its way.', note: 'Text on an order with nothing dispatched yet' },
  'states.degradedHead': { en: 'Live updates paused', note: 'Heading of the notice when the courier network cannot be reached', max: 60 },
  'states.degradedBody': { en: 'We can\'t reach the courier network right now. The shipment details below are still accurate.', note: 'Text of the notice when the courier network cannot be reached' },
  'states.disabledEyebrow': { en: 'Tracking', note: 'Small label above the title when order lookups are switched off', max: 40 },
  'states.disabledTitle': { en: 'Tracking isn\'t available right now', note: 'Title when order lookups are switched off on this shop', max: 80 },
  'states.disabledBody': { en: 'Order lookups are switched off on this shop. Message us with your order number and we\'ll check on it for you.', note: 'Text when order lookups are switched off on this shop' },
});
