import { defineTextArea } from '@/text/define.ts';

/** Area `wholesale`: the trade-list sheet, its basket bar, price-break ladder and rows (editable-text spec §6.1). */
export default defineTextArea('wholesale', {
  'page.title': { en: 'Trade list', max: 60 },
  'page.categoryEyebrow': { en: 'Category', max: 40 },
  'page.searchEyebrow': { en: 'Search', max: 40 },
  'page.loadFailedHint': { en: 'The list is still there — this was a hiccup between your browser and us.', max: 200 },
  'page.categoryMissingHint': { en: 'It may have been renamed or retired. The full list is still one tap away.', max: 200 },
  'page.showWholeList': { en: 'Show the whole list', max: 60 },
  'page.wholeList': { en: 'Whole list', max: 40 },
  'page.noMatchesHint': { en: 'Try a shorter word, or the product code from your last order.', max: 200 },
  'page.emptyHint': { en: "The list is empty for now — message us and we'll send the current sheet.", max: 200 },
  'search.withCode': { en: 'Search name or code', max: 60 },
  'search.plain': { en: 'Search', max: 40 },
  'tally.unit': { en: { one: 'line', other: 'lines' }, max: 30 },
  'tally.of': { en: 'of', max: 20 },
  'table.code': { en: 'Code', max: 30 },
  'table.product': { en: 'Product', max: 30 },
  'table.unit': { en: 'Unit', max: 30 },
  'table.bulk': { en: 'Bulk', max: 30 },
  'table.line': { en: 'Line', max: 30 },
  'table.qty': { en: 'Qty', max: 30 },
  'bar.lines': { en: { one: '{count} line', other: '{count} lines' }, max: 40 },
  'bar.units': { en: { one: '{count} unit', other: '{count} units' }, max: 40 },
  'bar.tally': { en: '{lines} · {units}', max: 80 },
  'bar.ariaLabel': { en: 'View basket — {lines}, {units}, {subtotal}', max: 160 },
  'bar.viewBasket': { en: 'View basket', max: 40 },
  'ladder.minUnits': { en: '{min}+ units', max: 40 },
  'ladder.yourPrice': { en: 'your price', max: 40 },
  'row.min': { en: 'Min {count}', max: 40 },
  'row.bulkPriceApplied': { en: 'Bulk price applied, {percent}% off — show the price breaks for {name}', max: 160 },
  'row.showBreaks': { en: 'Show the price breaks for {name}', max: 120 },
  'row.bulk': { en: 'Bulk', max: 30 },
  'row.removeAria': { en: 'Remove {name} from the order', max: 120 },
});
