import { defineTextArea } from '@/text/define.ts';

/** Area `wholesale`: the trade-list sheet, its basket bar, price-break ladder and rows (editable-text spec §6.1). */
export default defineTextArea('wholesale', {
  'page.title': { en: 'Trade list', note: 'Heading of the wholesale trade list, and the small label on its empty and error messages', max: 60 },
  'page.categoryEyebrow': { en: 'Category', note: "Small label above the unknown-category message on the trade list", max: 40 },
  'page.searchEyebrow': { en: 'Search', note: 'Small label above the "Nothing matches" message on the trade list', max: 40 },
  'page.loadFailedHint': { en: 'The list is still there — this was a hiccup between your browser and us.', note: "Text under the \"couldn't load\" heading on the trade list", max: 200 },
  'page.categoryMissingHint': { en: 'It may have been renamed or retired. The full list is still one tap away.', note: 'Text under the unknown-category heading on the trade list', max: 200 },
  'page.showWholeList': { en: 'Show the whole list', note: 'Button on the unknown-category message on the trade list', max: 60 },
  'page.wholeList': { en: 'Whole list', note: 'Link beside the heading that leaves an open category on the trade list', max: 40 },
  'page.noMatchesHint': { en: 'Try a shorter word, or the product code from your last order.', note: 'Text under "Nothing matches" on the trade list', max: 200 },
  'page.emptyHint': { en: "The list is empty for now — message us and we'll send the current sheet.", note: 'Text under "Nothing stocked here yet" on the trade list', max: 200 },
  'search.withCode': { en: 'Search name or code', note: 'Placeholder of the trade-list search box when product codes are shown', max: 60 },
  'search.plain': { en: 'Search', note: 'Placeholder of the trade-list search box when product codes are hidden', max: 40 },
  'tally.unit': { en: { one: 'line', other: 'lines' }, note: 'Word after the number of products in the trade-list heading tally', max: 30 },
  'tally.of': { en: 'of', note: 'Between the shown and total counts in the trade-list tally while a search is active', max: 20 },
  'table.code': { en: 'Code', note: 'Column heading: product code', max: 30 },
  'table.product': { en: 'Product', note: 'Column heading: product name', max: 30 },
  'table.unit': { en: 'Unit', note: 'Column heading: unit price', max: 30 },
  'table.bulk': { en: 'Bulk', note: 'Column heading: bulk price breaks', max: 30 },
  'table.line': { en: 'Line', note: 'Column heading: line total', max: 30 },
  'table.qty': { en: 'Qty', note: 'Column heading: quantity', max: 30 },
  'bar.lines': { en: { one: '{count} line', other: '{count} lines' }, note: 'Number of product lines in the trade-list basket bar', max: 40 },
  'bar.units': { en: { one: '{count} unit', other: '{count} units' }, note: 'Number of units in the trade-list basket bar', max: 40 },
  'bar.tally': { en: '{lines} · {units}', note: 'Visible tally in the basket bar; {lines} and {units} are the two counts above', max: 80 },
  'bar.ariaLabel': { en: 'View basket — {lines}, {units}, {subtotal}', note: 'Screen-reader label of the basket bar link', max: 160 },
  'bar.viewBasket': { en: 'View basket', note: 'Button text in the trade-list basket bar', max: 40 },
  'ladder.minUnits': { en: '{min}+ units', note: 'Price-break row: the quantity from which the price applies', max: 40 },
  'ladder.yourPrice': { en: 'your price', note: 'Tag on the price-break row that applies to the quantity in the basket', max: 40 },
  'row.min': { en: 'Min {count}', note: 'Chip on a trade-list row with a minimum order quantity', max: 40 },
  'row.bulkPriceApplied': { en: 'Bulk price applied, {percent}% off — show the price breaks for {name}', note: 'Screen-reader label of the bulk chip when a break applies; {percent} is the saving, {name} the product', max: 160 },
  'row.showBreaks': { en: 'Show the price breaks for {name}', note: 'Screen-reader label of the bulk chip when no break applies yet', max: 120 },
  'row.bulk': { en: 'Bulk', note: 'Bulk chip on a trade-list row that has price breaks', max: 30 },
  'row.removeAria': { en: 'Remove {name} from the order', note: 'Screen-reader label of Remove on an unavailable trade-list row', max: 120 },
});
