// Inlined into index.html (copy the string verbatim — a test checks it). Runs before React:
// replays the sf-theme-v2 payload applyDocumentTheme() stored (variables, root attributes, the
// Google Fonts link, title), so a returning visitor sees their template's palette and tokens on
// the first frame. Falls back to the previous release's sf-theme-v1 palette payload.
//
// Security: a stored payload is untrusted (devtools, a stale/foreign shape, a future release) —
// `A` allowlists attribute names to exactly what tokens.ts's ROOT_ATTRIBUTE_NAMES exports (a test
// pins the two lists equal), `V` allowlists CSS var names to `--sf-*`, and `G` allowlists
// fontsHref to a Google Fonts URL. Anything outside those is silently dropped, never applied. The
// v2 parse has its own try so a corrupt v2 entry still falls through to a valid v1 payload.
export const THEME_BOOTSTRAP = `(function(){try{var d=document.documentElement,A=['data-sf-template','data-sf-preset','data-sf-btn-fill','data-sf-input','data-sf-chassis','data-sf-label','data-sf-glass','data-mantine-color-scheme'],V=/^--sf-[a-z0-9-]+$/,G='https://fonts.googleapis.com/',k;try{var raw2=localStorage.getItem('sf-theme-v2');if(raw2){var s=JSON.parse(raw2);if(s&&s.v===2&&s.vars&&typeof s.vars==='object'&&s.attrs&&typeof s.attrs==='object'){for(k in s.vars){if(V.test(k)&&typeof s.vars[k]==='string')d.style.setProperty(k,s.vars[k])}for(k in s.attrs){if(A.indexOf(k)>-1&&typeof s.attrs[k]==='string')d.setAttribute(k,s.attrs[k])}d.style.colorScheme=d.getAttribute('data-mantine-color-scheme')||'dark';if(typeof s.fontsHref==='string'&&s.fontsHref.indexOf(G)===0){var l=document.createElement('link');l.id='sf-fonts';l.rel='stylesheet';l.href=s.fontsHref;document.head.appendChild(l)}if(typeof s.title==='string'&&s.title)document.title=s.title;return}}}catch(e2){}var raw=localStorage.getItem('sf-theme-v1');if(!raw)return;var s1=JSON.parse(raw),t=s1.theme,b=s1.brand,c=t.colors,dk=t.scheme==='dark',tt=dk?'#ffffff':'#000000';function p(h){return[1,3,5].map(function(i){return parseInt(h.slice(i,i+2),16)})}function mx(h,w,q){var a=p(h),z=p(w);return'#'+a.map(function(x,i){return Math.round(x+(z[i]-x)*q).toString(16).padStart(2,'0')}).join('')}var v={'--sf-bg':c.bg,'--sf-bg-deep':mx(c.bg,dk?'#000000':'#ffffff',.18),'--sf-surface':c.surface,'--sf-surface-2':mx(c.surface,tt,.07),'--sf-surface-3':mx(c.surface,tt,.14),'--sf-line':mx(c.surface,tt,.12),'--sf-line-strong':mx(c.surface,tt,.24),'--sf-text':c.text,'--sf-muted':c.muted,'--sf-faint':mx(c.muted,c.bg,.35),'--sf-primary':c.primary,'--sf-primary-soft':mx(c.primary,c.bg,.75),'--sf-success':c.success,'--sf-warn':c.warn,'--sf-danger':c.danger,'--sf-logo-h':b.logoHeight+'px'};for(k in v)d.style.setProperty(k,v[k]);d.setAttribute('data-mantine-color-scheme',t.scheme);d.style.colorScheme=t.scheme;if(b.title)document.title=b.title}catch(e){}})();`;
