import type { PartFamily } from '@/builder/parts.ts';
import { BOX, TEXT, VIS, type StyleKey, type StyleTarget } from '@/builder/style/model.ts';

const T = (target: StyleTarget, ...groups: ReadonlyArray<readonly StyleKey[]>) => ({ target, keys: groups.flat() });
/** Header parts: no vertical spacing, margins, maxWidth or textSize (stage-4 spec §9). */
export const BAR: readonly StyleKey[] = ['bg', 'fg', 'border', 'borderColor', 'borderStyle', 'radius', 'padX'];
const NO_FG = BAR.filter((k) => k !== 'fg');

/** Stage-4 spec §9, exactly. Keys may be added later, never removed. */
export const STAGE4_PARTS: Record<string, { family: PartFamily; style: { target: StyleTarget; keys: readonly StyleKey[] } }> = {
  HeaderBrand: { family: 'header', style: T('root', BAR) },
  HeaderBack: { family: 'header', style: T('root', BAR, VIS) },
  HeaderSearch: { family: 'header', style: T('root', NO_FG, VIS) },
  HeaderFilter: { family: 'header', style: T('root', BAR, VIS) },
  HeaderAccount: { family: 'header', style: T('root', BAR, VIS) },
  HeaderCart: { family: 'header', style: T('root', BAR, VIS) },
  CartHeading: { family: 'cart', style: T('root', BOX, TEXT) },
  CartLines: { family: 'cart', style: T('root', BOX) },
  CartEmpty: { family: 'cart', style: T('root', BOX, TEXT) },
  CartSummaryNotice: { family: 'cart-summary', style: T('root', BOX, TEXT, VIS) },
  CartSummaryTerms: { family: 'cart-summary', style: T('root', BOX, TEXT, VIS) },
  CartSummaryContinue: { family: 'cart-summary', style: T('root', BOX, TEXT, VIS) },
  CartSummarySubtotal: { family: 'cart-summary', style: T('root', BOX, TEXT) },
  CartSummaryCheckout: { family: 'cart-summary', style: T('wrap', BOX) },
  AccountGreeting: { family: 'account', style: T('root', BOX, TEXT) },
  AccountTabs: { family: 'account', style: T('root', BOX, TEXT) },
  OrdersHeading: { family: 'orders', style: T('root', BOX, TEXT, VIS) },
  OrdersMore: { family: 'orders', style: T('root', BOX, TEXT, VIS) },
  OrdersRows: { family: 'orders', style: T('root', BOX, TEXT) },
  OrdersEmpty: { family: 'orders', style: T('root', BOX, TEXT) },
  OrderHeading: { family: 'order', style: T('root', BOX, TEXT) },
  OrderItems: { family: 'order', style: T('root', BOX, TEXT) },
  OrderBackLink: { family: 'order', style: T('root', BOX, TEXT, VIS) },
  OrderBalance: { family: 'order', style: T('root', BOX, TEXT, VIS) },
  OrderPayments: { family: 'order', style: T('root', BOX, TEXT, VIS) },
  OrderParcels: { family: 'order', style: T('root', BOX, TEXT, VIS) },
  OrderAddress: { family: 'order', style: T('root', BOX, TEXT, VIS) },
  LoyaltyPoints: { family: 'loyalty', style: T('root', BOX, TEXT) },
  LoyaltyRewards: { family: 'loyalty', style: T('root', BOX, TEXT) },
  LoyaltyCredit: { family: 'loyalty', style: T('root', BOX, TEXT, VIS) },
  LoyaltyNoPoints: { family: 'loyalty', style: T('root', BOX, TEXT, VIS) },
  ReferralCode: { family: 'referrals', style: T('root', BOX, TEXT) },
  ReferralShare: { family: 'referrals', style: T('wrap', BOX, TEXT, VIS) },
  ReferralStats: { family: 'referrals', style: T('root', BOX, TEXT, VIS) },
  ReferralReferrer: { family: 'referrals', style: T('root', BOX, VIS) },
  ProfileDetails: { family: 'profile', style: T('wrap', BOX, TEXT, VIS) },
  ProfileChannels: { family: 'profile', style: T('root', BOX, TEXT, VIS) },
  ProfileContact: { family: 'profile', style: T('root', BOX, TEXT, VIS) },
  ProfileBotSwitch: { family: 'profile', style: T('root', BOX, TEXT, VIS) },
  ProfileSignOut: { family: 'profile', style: T('root', BOX) },
  LoginHeading: { family: 'login', style: T('root', BOX, TEXT) },
  LoginMethods: { family: 'login', style: T('root', BOX) },
  PaymentMark: { family: 'payment', style: T('root', BOX, VIS) },
  PaymentEyebrow: { family: 'payment', style: T('root', BOX, TEXT, VIS) },
  PaymentMessage: { family: 'payment', style: T('root', BOX, TEXT, VIS) },
  PaymentHeadline: { family: 'payment', style: T('root', BOX, TEXT) },
  PaymentReference: { family: 'payment', style: T('root', BOX, TEXT, VIS) },
  PaymentActions: { family: 'payment', style: T('root', BOX, VIS) },
  PaymentContact: { family: 'payment', style: T('root', BOX, VIS) },
  PaymentBack: { family: 'payment', style: T('root', BOX, VIS) },
  TrackingIntro: { family: 'tracking', style: T('root', BOX, TEXT) },
  TrackingState: { family: 'tracking', style: T('wrap', BOX) },
  TrackingParcels: { family: 'tracking', style: T('wrap', BOX) },
  TrackingForm: { family: 'tracking', style: T('root', BOX) },
  TrackingHero: { family: 'tracking', style: T('root', BOX) },
  TrackingProgress: { family: 'tracking', style: T('root', BOX, VIS) },
  TrackingRefresh: { family: 'tracking', style: T('root', BOX, VIS) },
  TrackingNotice: { family: 'tracking', style: T('root', BOX, VIS) },
  VerifyIntro: { family: 'verify', style: T('root', BOX, TEXT) },
  VerifyResult: { family: 'verify', style: T('root', BOX, TEXT) },
  VerifyFields: { family: 'verify', style: T('root', BOX) },
  VerifyBack: { family: 'verify', style: T('root', BOX, VIS) },
};

export const STAGE4_CONTAINERS: Record<string, PartFamily> = {
  Header: 'header', CartContents: 'cart', CartSummary: 'cart-summary', AccountNav: 'account', OrdersList: 'orders',
  OrderDetail: 'order', Loyalty: 'loyalty', Referrals: 'referrals', Profile: 'profile', LoginOptions: 'login',
  PaymentSuccess: 'payment', PaymentCancel: 'payment', OrderPlaced: 'payment', TrackingLookup: 'tracking', VerifyForm: 'verify',
};
