export declare const RESERVED_DIRS: readonly string[];
export declare const TEMPLATE_ID_RE: RegExp;
export declare const SHA_RE: RegExp;
export declare const CONTRACT_SPECIFIERS: readonly string[];
export declare const DEFINE_SPECIFIERS: readonly string[];
export declare const ALLOWED_PACKAGES: readonly string[];
export declare const REPO_RE: RegExp;
export declare const SOURCE_FILE_RE: RegExp;
export declare const STYLE_LANGUAGE_FILE_RE: RegExp;
export declare const CSS_MODULE_FILE_RE: RegExp;
export declare const CSS_FILE_RE: RegExp;
export declare const ALLOWED_CSS_QUERY_RE: RegExp;
